/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.secrets;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.secrets.V1beta1SecretExporterSpecTargetNamespaces;
import dev.educates.secrets.V1beta1SecretExporterSpecTargetSecret;
import dev.educates.secrets.V1beta1SecretImporterSpecCopyAuthorization;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1SecretExporterSpecRules
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T17:36:32.479Z[Etc/UTC]")
public class V1beta1SecretExporterSpecRules {
  public static final String SERIALIZED_NAME_COPY_AUTHORIZATION = "copyAuthorization";
  @SerializedName(SERIALIZED_NAME_COPY_AUTHORIZATION)
  private V1beta1SecretImporterSpecCopyAuthorization copyAuthorization;

  public static final String SERIALIZED_NAME_TARGET_NAMESPACES = "targetNamespaces";
  @SerializedName(SERIALIZED_NAME_TARGET_NAMESPACES)
  private V1beta1SecretExporterSpecTargetNamespaces targetNamespaces;

  public static final String SERIALIZED_NAME_TARGET_SECRET = "targetSecret";
  @SerializedName(SERIALIZED_NAME_TARGET_SECRET)
  private V1beta1SecretExporterSpecTargetSecret targetSecret;


  public V1beta1SecretExporterSpecRules copyAuthorization(V1beta1SecretImporterSpecCopyAuthorization copyAuthorization) {
    
    this.copyAuthorization = copyAuthorization;
    return this;
  }

   /**
   * Get copyAuthorization
   * @return copyAuthorization
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SecretImporterSpecCopyAuthorization getCopyAuthorization() {
    return copyAuthorization;
  }


  public void setCopyAuthorization(V1beta1SecretImporterSpecCopyAuthorization copyAuthorization) {
    this.copyAuthorization = copyAuthorization;
  }


  public V1beta1SecretExporterSpecRules targetNamespaces(V1beta1SecretExporterSpecTargetNamespaces targetNamespaces) {
    
    this.targetNamespaces = targetNamespaces;
    return this;
  }

   /**
   * Get targetNamespaces
   * @return targetNamespaces
  **/
  @ApiModelProperty(required = true, value = "")

  public V1beta1SecretExporterSpecTargetNamespaces getTargetNamespaces() {
    return targetNamespaces;
  }


  public void setTargetNamespaces(V1beta1SecretExporterSpecTargetNamespaces targetNamespaces) {
    this.targetNamespaces = targetNamespaces;
  }


  public V1beta1SecretExporterSpecRules targetSecret(V1beta1SecretExporterSpecTargetSecret targetSecret) {
    
    this.targetSecret = targetSecret;
    return this;
  }

   /**
   * Get targetSecret
   * @return targetSecret
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SecretExporterSpecTargetSecret getTargetSecret() {
    return targetSecret;
  }


  public void setTargetSecret(V1beta1SecretExporterSpecTargetSecret targetSecret) {
    this.targetSecret = targetSecret;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SecretExporterSpecRules v1beta1SecretExporterSpecRules = (V1beta1SecretExporterSpecRules) o;
    return Objects.equals(this.copyAuthorization, v1beta1SecretExporterSpecRules.copyAuthorization) &&
        Objects.equals(this.targetNamespaces, v1beta1SecretExporterSpecRules.targetNamespaces) &&
        Objects.equals(this.targetSecret, v1beta1SecretExporterSpecRules.targetSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(copyAuthorization, targetNamespaces, targetSecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SecretExporterSpecRules {\n");
    sb.append("    copyAuthorization: ").append(toIndentedString(copyAuthorization)).append("\n");
    sb.append("    targetNamespaces: ").append(toIndentedString(targetNamespaces)).append("\n");
    sb.append("    targetSecret: ").append(toIndentedString(targetSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

