/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.secrets;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.secrets.V1beta1SecretImporterSpecCopyAuthorization;
import dev.educates.secrets.V1beta1SecretImporterSpecSourceNamespaces;
import dev.educates.secrets.V1beta1SecretImporterSpecSourceSecret;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1SecretImporterSpec
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T17:36:32.479Z[Etc/UTC]")
public class V1beta1SecretImporterSpec {
  public static final String SERIALIZED_NAME_COPY_AUTHORIZATION = "copyAuthorization";
  @SerializedName(SERIALIZED_NAME_COPY_AUTHORIZATION)
  private V1beta1SecretImporterSpecCopyAuthorization copyAuthorization;

  public static final String SERIALIZED_NAME_SOURCE_NAMESPACES = "sourceNamespaces";
  @SerializedName(SERIALIZED_NAME_SOURCE_NAMESPACES)
  private V1beta1SecretImporterSpecSourceNamespaces sourceNamespaces;

  public static final String SERIALIZED_NAME_SOURCE_SECRET = "sourceSecret";
  @SerializedName(SERIALIZED_NAME_SOURCE_SECRET)
  private V1beta1SecretImporterSpecSourceSecret sourceSecret;


  public V1beta1SecretImporterSpec copyAuthorization(V1beta1SecretImporterSpecCopyAuthorization copyAuthorization) {
    
    this.copyAuthorization = copyAuthorization;
    return this;
  }

   /**
   * Get copyAuthorization
   * @return copyAuthorization
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SecretImporterSpecCopyAuthorization getCopyAuthorization() {
    return copyAuthorization;
  }


  public void setCopyAuthorization(V1beta1SecretImporterSpecCopyAuthorization copyAuthorization) {
    this.copyAuthorization = copyAuthorization;
  }


  public V1beta1SecretImporterSpec sourceNamespaces(V1beta1SecretImporterSpecSourceNamespaces sourceNamespaces) {
    
    this.sourceNamespaces = sourceNamespaces;
    return this;
  }

   /**
   * Get sourceNamespaces
   * @return sourceNamespaces
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SecretImporterSpecSourceNamespaces getSourceNamespaces() {
    return sourceNamespaces;
  }


  public void setSourceNamespaces(V1beta1SecretImporterSpecSourceNamespaces sourceNamespaces) {
    this.sourceNamespaces = sourceNamespaces;
  }


  public V1beta1SecretImporterSpec sourceSecret(V1beta1SecretImporterSpecSourceSecret sourceSecret) {
    
    this.sourceSecret = sourceSecret;
    return this;
  }

   /**
   * Get sourceSecret
   * @return sourceSecret
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SecretImporterSpecSourceSecret getSourceSecret() {
    return sourceSecret;
  }


  public void setSourceSecret(V1beta1SecretImporterSpecSourceSecret sourceSecret) {
    this.sourceSecret = sourceSecret;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SecretImporterSpec v1beta1SecretImporterSpec = (V1beta1SecretImporterSpec) o;
    return Objects.equals(this.copyAuthorization, v1beta1SecretImporterSpec.copyAuthorization) &&
        Objects.equals(this.sourceNamespaces, v1beta1SecretImporterSpec.sourceNamespaces) &&
        Objects.equals(this.sourceSecret, v1beta1SecretImporterSpec.sourceSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(copyAuthorization, sourceNamespaces, sourceSecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SecretImporterSpec {\n");
    sb.append("    copyAuthorization: ").append(toIndentedString(copyAuthorization)).append("\n");
    sb.append("    sourceNamespaces: ").append(toIndentedString(sourceNamespaces)).append("\n");
    sb.append("    sourceSecret: ").append(toIndentedString(sourceSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

