/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.secrets;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.secrets.V1beta1SecretCopierSpecCopyAuthorization;
import dev.educates.secrets.V1beta1SecretCopierSpecSourceSecret;
import dev.educates.secrets.V1beta1SecretExporterSpecTargetNamespaces;
import dev.educates.secrets.V1beta1SecretExporterSpecTargetSecret;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1SecretCopierSpecRules
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T17:36:32.479Z[Etc/UTC]")
public class V1beta1SecretCopierSpecRules {
  public static final String SERIALIZED_NAME_COPY_AUTHORIZATION = "copyAuthorization";
  @SerializedName(SERIALIZED_NAME_COPY_AUTHORIZATION)
  private V1beta1SecretCopierSpecCopyAuthorization copyAuthorization;

  /**
   * Gets or Sets reclaimPolicy
   */
  @JsonAdapter(ReclaimPolicyEnum.Adapter.class)
  public enum ReclaimPolicyEnum {
    DELETE("Delete"),
    
    RETAIN("Retain");

    private String value;

    ReclaimPolicyEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static ReclaimPolicyEnum fromValue(String value) {
      for (ReclaimPolicyEnum b : ReclaimPolicyEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<ReclaimPolicyEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final ReclaimPolicyEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public ReclaimPolicyEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return ReclaimPolicyEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RECLAIM_POLICY = "reclaimPolicy";
  @SerializedName(SERIALIZED_NAME_RECLAIM_POLICY)
  private ReclaimPolicyEnum reclaimPolicy;

  public static final String SERIALIZED_NAME_SOURCE_SECRET = "sourceSecret";
  @SerializedName(SERIALIZED_NAME_SOURCE_SECRET)
  private V1beta1SecretCopierSpecSourceSecret sourceSecret;

  public static final String SERIALIZED_NAME_TARGET_NAMESPACES = "targetNamespaces";
  @SerializedName(SERIALIZED_NAME_TARGET_NAMESPACES)
  private V1beta1SecretExporterSpecTargetNamespaces targetNamespaces;

  public static final String SERIALIZED_NAME_TARGET_SECRET = "targetSecret";
  @SerializedName(SERIALIZED_NAME_TARGET_SECRET)
  private V1beta1SecretExporterSpecTargetSecret targetSecret;


  public V1beta1SecretCopierSpecRules copyAuthorization(V1beta1SecretCopierSpecCopyAuthorization copyAuthorization) {
    
    this.copyAuthorization = copyAuthorization;
    return this;
  }

   /**
   * Get copyAuthorization
   * @return copyAuthorization
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SecretCopierSpecCopyAuthorization getCopyAuthorization() {
    return copyAuthorization;
  }


  public void setCopyAuthorization(V1beta1SecretCopierSpecCopyAuthorization copyAuthorization) {
    this.copyAuthorization = copyAuthorization;
  }


  public V1beta1SecretCopierSpecRules reclaimPolicy(ReclaimPolicyEnum reclaimPolicy) {
    
    this.reclaimPolicy = reclaimPolicy;
    return this;
  }

   /**
   * Get reclaimPolicy
   * @return reclaimPolicy
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public ReclaimPolicyEnum getReclaimPolicy() {
    return reclaimPolicy;
  }


  public void setReclaimPolicy(ReclaimPolicyEnum reclaimPolicy) {
    this.reclaimPolicy = reclaimPolicy;
  }


  public V1beta1SecretCopierSpecRules sourceSecret(V1beta1SecretCopierSpecSourceSecret sourceSecret) {
    
    this.sourceSecret = sourceSecret;
    return this;
  }

   /**
   * Get sourceSecret
   * @return sourceSecret
  **/
  @ApiModelProperty(required = true, value = "")

  public V1beta1SecretCopierSpecSourceSecret getSourceSecret() {
    return sourceSecret;
  }


  public void setSourceSecret(V1beta1SecretCopierSpecSourceSecret sourceSecret) {
    this.sourceSecret = sourceSecret;
  }


  public V1beta1SecretCopierSpecRules targetNamespaces(V1beta1SecretExporterSpecTargetNamespaces targetNamespaces) {
    
    this.targetNamespaces = targetNamespaces;
    return this;
  }

   /**
   * Get targetNamespaces
   * @return targetNamespaces
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SecretExporterSpecTargetNamespaces getTargetNamespaces() {
    return targetNamespaces;
  }


  public void setTargetNamespaces(V1beta1SecretExporterSpecTargetNamespaces targetNamespaces) {
    this.targetNamespaces = targetNamespaces;
  }


  public V1beta1SecretCopierSpecRules targetSecret(V1beta1SecretExporterSpecTargetSecret targetSecret) {
    
    this.targetSecret = targetSecret;
    return this;
  }

   /**
   * Get targetSecret
   * @return targetSecret
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SecretExporterSpecTargetSecret getTargetSecret() {
    return targetSecret;
  }


  public void setTargetSecret(V1beta1SecretExporterSpecTargetSecret targetSecret) {
    this.targetSecret = targetSecret;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SecretCopierSpecRules v1beta1SecretCopierSpecRules = (V1beta1SecretCopierSpecRules) o;
    return Objects.equals(this.copyAuthorization, v1beta1SecretCopierSpecRules.copyAuthorization) &&
        Objects.equals(this.reclaimPolicy, v1beta1SecretCopierSpecRules.reclaimPolicy) &&
        Objects.equals(this.sourceSecret, v1beta1SecretCopierSpecRules.sourceSecret) &&
        Objects.equals(this.targetNamespaces, v1beta1SecretCopierSpecRules.targetNamespaces) &&
        Objects.equals(this.targetSecret, v1beta1SecretCopierSpecRules.targetSecret);
  }

  @Override
  public int hashCode() {
    return Objects.hash(copyAuthorization, reclaimPolicy, sourceSecret, targetNamespaces, targetSecret);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SecretCopierSpecRules {\n");
    sb.append("    copyAuthorization: ").append(toIndentedString(copyAuthorization)).append("\n");
    sb.append("    reclaimPolicy: ").append(toIndentedString(reclaimPolicy)).append("\n");
    sb.append("    sourceSecret: ").append(toIndentedString(sourceSecret)).append("\n");
    sb.append("    targetNamespaces: ").append(toIndentedString(targetNamespaces)).append("\n");
    sb.append("    targetSecret: ").append(toIndentedString(targetSecret)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

