/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.secrets;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.secrets.V1beta1SecretInjectorSpecServiceAccountsLabelSelectorMatchExpressions;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1SecretInjectorSpecServiceAccountsLabelSelector
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T17:36:32.479Z[Etc/UTC]")
public class V1beta1SecretInjectorSpecServiceAccountsLabelSelector {
  public static final String SERIALIZED_NAME_MATCH_EXPRESSIONS = "matchExpressions";
  @SerializedName(SERIALIZED_NAME_MATCH_EXPRESSIONS)
  private List<V1beta1SecretInjectorSpecServiceAccountsLabelSelectorMatchExpressions> matchExpressions = null;

  public static final String SERIALIZED_NAME_MATCH_LABELS = "matchLabels";
  @SerializedName(SERIALIZED_NAME_MATCH_LABELS)
  private Object matchLabels;


  public V1beta1SecretInjectorSpecServiceAccountsLabelSelector matchExpressions(List<V1beta1SecretInjectorSpecServiceAccountsLabelSelectorMatchExpressions> matchExpressions) {
    
    this.matchExpressions = matchExpressions;
    return this;
  }

  public V1beta1SecretInjectorSpecServiceAccountsLabelSelector addMatchExpressionsItem(V1beta1SecretInjectorSpecServiceAccountsLabelSelectorMatchExpressions matchExpressionsItem) {
    if (this.matchExpressions == null) {
      this.matchExpressions = new ArrayList<>();
    }
    this.matchExpressions.add(matchExpressionsItem);
    return this;
  }

   /**
   * Get matchExpressions
   * @return matchExpressions
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1SecretInjectorSpecServiceAccountsLabelSelectorMatchExpressions> getMatchExpressions() {
    return matchExpressions;
  }


  public void setMatchExpressions(List<V1beta1SecretInjectorSpecServiceAccountsLabelSelectorMatchExpressions> matchExpressions) {
    this.matchExpressions = matchExpressions;
  }


  public V1beta1SecretInjectorSpecServiceAccountsLabelSelector matchLabels(Object matchLabels) {
    
    this.matchLabels = matchLabels;
    return this;
  }

   /**
   * Get matchLabels
   * @return matchLabels
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getMatchLabels() {
    return matchLabels;
  }


  public void setMatchLabels(Object matchLabels) {
    this.matchLabels = matchLabels;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SecretInjectorSpecServiceAccountsLabelSelector v1beta1SecretInjectorSpecServiceAccountsLabelSelector = (V1beta1SecretInjectorSpecServiceAccountsLabelSelector) o;
    return Objects.equals(this.matchExpressions, v1beta1SecretInjectorSpecServiceAccountsLabelSelector.matchExpressions) &&
        Objects.equals(this.matchLabels, v1beta1SecretInjectorSpecServiceAccountsLabelSelector.matchLabels);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchExpressions, matchLabels);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SecretInjectorSpecServiceAccountsLabelSelector {\n");
    sb.append("    matchExpressions: ").append(toIndentedString(matchExpressions)).append("\n");
    sb.append("    matchLabels: ").append(toIndentedString(matchLabels)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

