/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.secrets;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.secrets.V1beta1SecretExporterSpecTargetNamespacesOwnerSelectorMatchOwners;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1SecretExporterSpecTargetNamespacesOwnerSelector
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T17:36:32.479Z[Etc/UTC]")
public class V1beta1SecretExporterSpecTargetNamespacesOwnerSelector {
  public static final String SERIALIZED_NAME_MATCH_OWNERS = "matchOwners";
  @SerializedName(SERIALIZED_NAME_MATCH_OWNERS)
  private List<V1beta1SecretExporterSpecTargetNamespacesOwnerSelectorMatchOwners> matchOwners = new ArrayList<>();


  public V1beta1SecretExporterSpecTargetNamespacesOwnerSelector matchOwners(List<V1beta1SecretExporterSpecTargetNamespacesOwnerSelectorMatchOwners> matchOwners) {
    
    this.matchOwners = matchOwners;
    return this;
  }

  public V1beta1SecretExporterSpecTargetNamespacesOwnerSelector addMatchOwnersItem(V1beta1SecretExporterSpecTargetNamespacesOwnerSelectorMatchOwners matchOwnersItem) {
    this.matchOwners.add(matchOwnersItem);
    return this;
  }

   /**
   * Get matchOwners
   * @return matchOwners
  **/
  @ApiModelProperty(required = true, value = "")

  public List<V1beta1SecretExporterSpecTargetNamespacesOwnerSelectorMatchOwners> getMatchOwners() {
    return matchOwners;
  }


  public void setMatchOwners(List<V1beta1SecretExporterSpecTargetNamespacesOwnerSelectorMatchOwners> matchOwners) {
    this.matchOwners = matchOwners;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SecretExporterSpecTargetNamespacesOwnerSelector v1beta1SecretExporterSpecTargetNamespacesOwnerSelector = (V1beta1SecretExporterSpecTargetNamespacesOwnerSelector) o;
    return Objects.equals(this.matchOwners, v1beta1SecretExporterSpecTargetNamespacesOwnerSelector.matchOwners);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchOwners);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SecretExporterSpecTargetNamespacesOwnerSelector {\n");
    sb.append("    matchOwners: ").append(toIndentedString(matchOwners)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

