/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.secrets;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1SecretInjectorSpecServiceAccountsNameSelector
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T17:36:32.479Z[Etc/UTC]")
public class V1beta1SecretInjectorSpecServiceAccountsNameSelector {
  public static final String SERIALIZED_NAME_MATCH_NAMES = "matchNames";
  @SerializedName(SERIALIZED_NAME_MATCH_NAMES)
  private List<String> matchNames = new ArrayList<>();


  public V1beta1SecretInjectorSpecServiceAccountsNameSelector matchNames(List<String> matchNames) {
    
    this.matchNames = matchNames;
    return this;
  }

  public V1beta1SecretInjectorSpecServiceAccountsNameSelector addMatchNamesItem(String matchNamesItem) {
    this.matchNames.add(matchNamesItem);
    return this;
  }

   /**
   * Get matchNames
   * @return matchNames
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getMatchNames() {
    return matchNames;
  }


  public void setMatchNames(List<String> matchNames) {
    this.matchNames = matchNames;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SecretInjectorSpecServiceAccountsNameSelector v1beta1SecretInjectorSpecServiceAccountsNameSelector = (V1beta1SecretInjectorSpecServiceAccountsNameSelector) o;
    return Objects.equals(this.matchNames, v1beta1SecretInjectorSpecServiceAccountsNameSelector.matchNames);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchNames);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SecretInjectorSpecServiceAccountsNameSelector {\n");
    sb.append("    matchNames: ").append(toIndentedString(matchNames)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

