/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.secrets;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1SecretInjectorSpecTargetNamespacesUidSelector
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T17:36:32.479Z[Etc/UTC]")
public class V1beta1SecretInjectorSpecTargetNamespacesUidSelector {
  public static final String SERIALIZED_NAME_MATCH_U_I_DS = "matchUIDs";
  @SerializedName(SERIALIZED_NAME_MATCH_U_I_DS)
  private List<String> matchUIDs = new ArrayList<>();


  public V1beta1SecretInjectorSpecTargetNamespacesUidSelector matchUIDs(List<String> matchUIDs) {
    
    this.matchUIDs = matchUIDs;
    return this;
  }

  public V1beta1SecretInjectorSpecTargetNamespacesUidSelector addMatchUIDsItem(String matchUIDsItem) {
    this.matchUIDs.add(matchUIDsItem);
    return this;
  }

   /**
   * Get matchUIDs
   * @return matchUIDs
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getMatchUIDs() {
    return matchUIDs;
  }


  public void setMatchUIDs(List<String> matchUIDs) {
    this.matchUIDs = matchUIDs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SecretInjectorSpecTargetNamespacesUidSelector v1beta1SecretInjectorSpecTargetNamespacesUidSelector = (V1beta1SecretInjectorSpecTargetNamespacesUidSelector) o;
    return Objects.equals(this.matchUIDs, v1beta1SecretInjectorSpecTargetNamespacesUidSelector.matchUIDs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(matchUIDs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SecretInjectorSpecTargetNamespacesUidSelector {\n");
    sb.append("    matchUIDs: ").append(toIndentedString(matchUIDs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

