spring:
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  ***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
***REMOVED***
''
management:
  server:
    port: 8090
  endpoints:
    web:
      exposure:
        include: "*"