/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1WorkshopSpecEnvironmentAssetsFiles;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1WorkshopSpecWorkshopPackages
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSpecWorkshopPackages {
  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private List<V1beta1WorkshopSpecEnvironmentAssetsFiles> files = new ArrayList<>();

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public V1beta1WorkshopSpecWorkshopPackages files(List<V1beta1WorkshopSpecEnvironmentAssetsFiles> files) {
    
    this.files = files;
    return this;
  }

  public V1beta1WorkshopSpecWorkshopPackages addFilesItem(V1beta1WorkshopSpecEnvironmentAssetsFiles filesItem) {
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @ApiModelProperty(required = true, value = "")

  public List<V1beta1WorkshopSpecEnvironmentAssetsFiles> getFiles() {
    return files;
  }


  public void setFiles(List<V1beta1WorkshopSpecEnvironmentAssetsFiles> files) {
    this.files = files;
  }


  public V1beta1WorkshopSpecWorkshopPackages name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @ApiModelProperty(required = true, value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSpecWorkshopPackages v1beta1WorkshopSpecWorkshopPackages = (V1beta1WorkshopSpecWorkshopPackages) o;
    return Objects.equals(this.files, v1beta1WorkshopSpecWorkshopPackages.files) &&
        Objects.equals(this.name, v1beta1WorkshopSpecWorkshopPackages.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(files, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSpecWorkshopPackages {\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

