/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1TrainingPortalSpecPortalLabels;
import dev.educates.training.V1beta1WorkshopSpecSessionApplicationsWorkshopProxyPathRewrite;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1WorkshopSpecSessionApplicationsWorkshopProxy
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSpecSessionApplicationsWorkshopProxy {
  public static final String SERIALIZED_NAME_CHANGE_ORIGIN = "changeOrigin";
  @SerializedName(SERIALIZED_NAME_CHANGE_ORIGIN)
  private Boolean changeOrigin;

  public static final String SERIALIZED_NAME_HEADERS = "headers";
  @SerializedName(SERIALIZED_NAME_HEADERS)
  private List<V1beta1TrainingPortalSpecPortalLabels> headers = null;

  public static final String SERIALIZED_NAME_HOST = "host";
  @SerializedName(SERIALIZED_NAME_HOST)
  private String host;

  public static final String SERIALIZED_NAME_PATH_REWRITE = "pathRewrite";
  @SerializedName(SERIALIZED_NAME_PATH_REWRITE)
  private List<V1beta1WorkshopSpecSessionApplicationsWorkshopProxyPathRewrite> pathRewrite = null;

  public static final String SERIALIZED_NAME_PORT = "port";
  @SerializedName(SERIALIZED_NAME_PORT)
  private Integer port;

  public static final String SERIALIZED_NAME_PROTOCOL = "protocol";
  @SerializedName(SERIALIZED_NAME_PROTOCOL)
  private String protocol;


  public V1beta1WorkshopSpecSessionApplicationsWorkshopProxy changeOrigin(Boolean changeOrigin) {
    
    this.changeOrigin = changeOrigin;
    return this;
  }

   /**
   * Get changeOrigin
   * @return changeOrigin
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getChangeOrigin() {
    return changeOrigin;
  }


  public void setChangeOrigin(Boolean changeOrigin) {
    this.changeOrigin = changeOrigin;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshopProxy headers(List<V1beta1TrainingPortalSpecPortalLabels> headers) {
    
    this.headers = headers;
    return this;
  }

  public V1beta1WorkshopSpecSessionApplicationsWorkshopProxy addHeadersItem(V1beta1TrainingPortalSpecPortalLabels headersItem) {
    if (this.headers == null) {
      this.headers = new ArrayList<>();
    }
    this.headers.add(headersItem);
    return this;
  }

   /**
   * Get headers
   * @return headers
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1TrainingPortalSpecPortalLabels> getHeaders() {
    return headers;
  }


  public void setHeaders(List<V1beta1TrainingPortalSpecPortalLabels> headers) {
    this.headers = headers;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshopProxy host(String host) {
    
    this.host = host;
    return this;
  }

   /**
   * Get host
   * @return host
  **/
  @ApiModelProperty(required = true, value = "")

  public String getHost() {
    return host;
  }


  public void setHost(String host) {
    this.host = host;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshopProxy pathRewrite(List<V1beta1WorkshopSpecSessionApplicationsWorkshopProxyPathRewrite> pathRewrite) {
    
    this.pathRewrite = pathRewrite;
    return this;
  }

  public V1beta1WorkshopSpecSessionApplicationsWorkshopProxy addPathRewriteItem(V1beta1WorkshopSpecSessionApplicationsWorkshopProxyPathRewrite pathRewriteItem) {
    if (this.pathRewrite == null) {
      this.pathRewrite = new ArrayList<>();
    }
    this.pathRewrite.add(pathRewriteItem);
    return this;
  }

   /**
   * Get pathRewrite
   * @return pathRewrite
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1WorkshopSpecSessionApplicationsWorkshopProxyPathRewrite> getPathRewrite() {
    return pathRewrite;
  }


  public void setPathRewrite(List<V1beta1WorkshopSpecSessionApplicationsWorkshopProxyPathRewrite> pathRewrite) {
    this.pathRewrite = pathRewrite;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshopProxy port(Integer port) {
    
    this.port = port;
    return this;
  }

   /**
   * Get port
   * @return port
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getPort() {
    return port;
  }


  public void setPort(Integer port) {
    this.port = port;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshopProxy protocol(String protocol) {
    
    this.protocol = protocol;
    return this;
  }

   /**
   * Get protocol
   * @return protocol
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getProtocol() {
    return protocol;
  }


  public void setProtocol(String protocol) {
    this.protocol = protocol;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSpecSessionApplicationsWorkshopProxy v1beta1WorkshopSpecSessionApplicationsWorkshopProxy = (V1beta1WorkshopSpecSessionApplicationsWorkshopProxy) o;
    return Objects.equals(this.changeOrigin, v1beta1WorkshopSpecSessionApplicationsWorkshopProxy.changeOrigin) &&
        Objects.equals(this.headers, v1beta1WorkshopSpecSessionApplicationsWorkshopProxy.headers) &&
        Objects.equals(this.host, v1beta1WorkshopSpecSessionApplicationsWorkshopProxy.host) &&
        Objects.equals(this.pathRewrite, v1beta1WorkshopSpecSessionApplicationsWorkshopProxy.pathRewrite) &&
        Objects.equals(this.port, v1beta1WorkshopSpecSessionApplicationsWorkshopProxy.port) &&
        Objects.equals(this.protocol, v1beta1WorkshopSpecSessionApplicationsWorkshopProxy.protocol);
  }

  @Override
  public int hashCode() {
    return Objects.hash(changeOrigin, headers, host, pathRewrite, port, protocol);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSpecSessionApplicationsWorkshopProxy {\n");
    sb.append("    changeOrigin: ").append(toIndentedString(changeOrigin)).append("\n");
    sb.append("    headers: ").append(toIndentedString(headers)).append("\n");
    sb.append("    host: ").append(toIndentedString(host)).append("\n");
    sb.append("    pathRewrite: ").append(toIndentedString(pathRewrite)).append("\n");
    sb.append("    port: ").append(toIndentedString(port)).append("\n");
    sb.append("    protocol: ").append(toIndentedString(protocol)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

