/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1WorkshopSpecEnvironmentAssetsInlinePathsFrom;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1WorkshopSpecEnvironmentAssetsInline
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSpecEnvironmentAssetsInline {
  public static final String SERIALIZED_NAME_PATHS = "paths";
  @SerializedName(SERIALIZED_NAME_PATHS)
  private Object paths;

  public static final String SERIALIZED_NAME_PATHS_FROM = "pathsFrom";
  @SerializedName(SERIALIZED_NAME_PATHS_FROM)
  private List<V1beta1WorkshopSpecEnvironmentAssetsInlinePathsFrom> pathsFrom = null;


  public V1beta1WorkshopSpecEnvironmentAssetsInline paths(Object paths) {
    
    this.paths = paths;
    return this;
  }

   /**
   * Get paths
   * @return paths
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getPaths() {
    return paths;
  }


  public void setPaths(Object paths) {
    this.paths = paths;
  }


  public V1beta1WorkshopSpecEnvironmentAssetsInline pathsFrom(List<V1beta1WorkshopSpecEnvironmentAssetsInlinePathsFrom> pathsFrom) {
    
    this.pathsFrom = pathsFrom;
    return this;
  }

  public V1beta1WorkshopSpecEnvironmentAssetsInline addPathsFromItem(V1beta1WorkshopSpecEnvironmentAssetsInlinePathsFrom pathsFromItem) {
    if (this.pathsFrom == null) {
      this.pathsFrom = new ArrayList<>();
    }
    this.pathsFrom.add(pathsFromItem);
    return this;
  }

   /**
   * Get pathsFrom
   * @return pathsFrom
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1WorkshopSpecEnvironmentAssetsInlinePathsFrom> getPathsFrom() {
    return pathsFrom;
  }


  public void setPathsFrom(List<V1beta1WorkshopSpecEnvironmentAssetsInlinePathsFrom> pathsFrom) {
    this.pathsFrom = pathsFrom;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSpecEnvironmentAssetsInline v1beta1WorkshopSpecEnvironmentAssetsInline = (V1beta1WorkshopSpecEnvironmentAssetsInline) o;
    return Objects.equals(this.paths, v1beta1WorkshopSpecEnvironmentAssetsInline.paths) &&
        Objects.equals(this.pathsFrom, v1beta1WorkshopSpecEnvironmentAssetsInline.pathsFrom);
  }

  @Override
  public int hashCode() {
    return Objects.hash(paths, pathsFrom);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSpecEnvironmentAssetsInline {\n");
    sb.append("    paths: ").append(toIndentedString(paths)).append("\n");
    sb.append("    pathsFrom: ").append(toIndentedString(pathsFrom)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

