/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1WorkshopSpecEnvironmentImagesContent;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1WorkshopSpecEnvironmentImagesRegistries
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSpecEnvironmentImagesRegistries {
  public static final String SERIALIZED_NAME_CONTENT = "content";
  @SerializedName(SERIALIZED_NAME_CONTENT)
  private List<V1beta1WorkshopSpecEnvironmentImagesContent> content = null;

  public static final String SERIALIZED_NAME_MAX_RETRIES = "maxRetries";
  @SerializedName(SERIALIZED_NAME_MAX_RETRIES)
  private Integer maxRetries;

  public static final String SERIALIZED_NAME_ON_DEMAND = "onDemand";
  @SerializedName(SERIALIZED_NAME_ON_DEMAND)
  private Boolean onDemand;

  public static final String SERIALIZED_NAME_ONLY_SIGNED = "onlySigned";
  @SerializedName(SERIALIZED_NAME_ONLY_SIGNED)
  private Boolean onlySigned;

  public static final String SERIALIZED_NAME_POLL_INTERVAL = "pollInterval";
  @SerializedName(SERIALIZED_NAME_POLL_INTERVAL)
  private String pollInterval;

  public static final String SERIALIZED_NAME_RETRY_DELAY = "retryDelay";
  @SerializedName(SERIALIZED_NAME_RETRY_DELAY)
  private String retryDelay;

  public static final String SERIALIZED_NAME_TLS_VERIFY = "tlsVerify";
  @SerializedName(SERIALIZED_NAME_TLS_VERIFY)
  private Boolean tlsVerify;

  public static final String SERIALIZED_NAME_URLS = "urls";
  @SerializedName(SERIALIZED_NAME_URLS)
  private List<String> urls = new ArrayList<>();


  public V1beta1WorkshopSpecEnvironmentImagesRegistries content(List<V1beta1WorkshopSpecEnvironmentImagesContent> content) {
    
    this.content = content;
    return this;
  }

  public V1beta1WorkshopSpecEnvironmentImagesRegistries addContentItem(V1beta1WorkshopSpecEnvironmentImagesContent contentItem) {
    if (this.content == null) {
      this.content = new ArrayList<>();
    }
    this.content.add(contentItem);
    return this;
  }

   /**
   * Get content
   * @return content
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1WorkshopSpecEnvironmentImagesContent> getContent() {
    return content;
  }


  public void setContent(List<V1beta1WorkshopSpecEnvironmentImagesContent> content) {
    this.content = content;
  }


  public V1beta1WorkshopSpecEnvironmentImagesRegistries maxRetries(Integer maxRetries) {
    
    this.maxRetries = maxRetries;
    return this;
  }

   /**
   * Get maxRetries
   * @return maxRetries
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMaxRetries() {
    return maxRetries;
  }


  public void setMaxRetries(Integer maxRetries) {
    this.maxRetries = maxRetries;
  }


  public V1beta1WorkshopSpecEnvironmentImagesRegistries onDemand(Boolean onDemand) {
    
    this.onDemand = onDemand;
    return this;
  }

   /**
   * Get onDemand
   * @return onDemand
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getOnDemand() {
    return onDemand;
  }


  public void setOnDemand(Boolean onDemand) {
    this.onDemand = onDemand;
  }


  public V1beta1WorkshopSpecEnvironmentImagesRegistries onlySigned(Boolean onlySigned) {
    
    this.onlySigned = onlySigned;
    return this;
  }

   /**
   * Get onlySigned
   * @return onlySigned
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getOnlySigned() {
    return onlySigned;
  }


  public void setOnlySigned(Boolean onlySigned) {
    this.onlySigned = onlySigned;
  }


  public V1beta1WorkshopSpecEnvironmentImagesRegistries pollInterval(String pollInterval) {
    
    this.pollInterval = pollInterval;
    return this;
  }

   /**
   * Get pollInterval
   * @return pollInterval
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPollInterval() {
    return pollInterval;
  }


  public void setPollInterval(String pollInterval) {
    this.pollInterval = pollInterval;
  }


  public V1beta1WorkshopSpecEnvironmentImagesRegistries retryDelay(String retryDelay) {
    
    this.retryDelay = retryDelay;
    return this;
  }

   /**
   * Get retryDelay
   * @return retryDelay
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getRetryDelay() {
    return retryDelay;
  }


  public void setRetryDelay(String retryDelay) {
    this.retryDelay = retryDelay;
  }


  public V1beta1WorkshopSpecEnvironmentImagesRegistries tlsVerify(Boolean tlsVerify) {
    
    this.tlsVerify = tlsVerify;
    return this;
  }

   /**
   * Get tlsVerify
   * @return tlsVerify
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getTlsVerify() {
    return tlsVerify;
  }


  public void setTlsVerify(Boolean tlsVerify) {
    this.tlsVerify = tlsVerify;
  }


  public V1beta1WorkshopSpecEnvironmentImagesRegistries urls(List<String> urls) {
    
    this.urls = urls;
    return this;
  }

  public V1beta1WorkshopSpecEnvironmentImagesRegistries addUrlsItem(String urlsItem) {
    this.urls.add(urlsItem);
    return this;
  }

   /**
   * Get urls
   * @return urls
  **/
  @ApiModelProperty(required = true, value = "")

  public List<String> getUrls() {
    return urls;
  }


  public void setUrls(List<String> urls) {
    this.urls = urls;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSpecEnvironmentImagesRegistries v1beta1WorkshopSpecEnvironmentImagesRegistries = (V1beta1WorkshopSpecEnvironmentImagesRegistries) o;
    return Objects.equals(this.content, v1beta1WorkshopSpecEnvironmentImagesRegistries.content) &&
        Objects.equals(this.maxRetries, v1beta1WorkshopSpecEnvironmentImagesRegistries.maxRetries) &&
        Objects.equals(this.onDemand, v1beta1WorkshopSpecEnvironmentImagesRegistries.onDemand) &&
        Objects.equals(this.onlySigned, v1beta1WorkshopSpecEnvironmentImagesRegistries.onlySigned) &&
        Objects.equals(this.pollInterval, v1beta1WorkshopSpecEnvironmentImagesRegistries.pollInterval) &&
        Objects.equals(this.retryDelay, v1beta1WorkshopSpecEnvironmentImagesRegistries.retryDelay) &&
        Objects.equals(this.tlsVerify, v1beta1WorkshopSpecEnvironmentImagesRegistries.tlsVerify) &&
        Objects.equals(this.urls, v1beta1WorkshopSpecEnvironmentImagesRegistries.urls);
  }

  @Override
  public int hashCode() {
    return Objects.hash(content, maxRetries, onDemand, onlySigned, pollInterval, retryDelay, tlsVerify, urls);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSpecEnvironmentImagesRegistries {\n");
    sb.append("    content: ").append(toIndentedString(content)).append("\n");
    sb.append("    maxRetries: ").append(toIndentedString(maxRetries)).append("\n");
    sb.append("    onDemand: ").append(toIndentedString(onDemand)).append("\n");
    sb.append("    onlySigned: ").append(toIndentedString(onlySigned)).append("\n");
    sb.append("    pollInterval: ").append(toIndentedString(pollInterval)).append("\n");
    sb.append("    retryDelay: ").append(toIndentedString(retryDelay)).append("\n");
    sb.append("    tlsVerify: ").append(toIndentedString(tlsVerify)).append("\n");
    sb.append("    urls: ").append(toIndentedString(urls)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

