/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1TrainingPortalStatusEducatesSecrets
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1TrainingPortalStatusEducatesSecrets {
  public static final String SERIALIZED_NAME_INGRESS = "ingress";
  @SerializedName(SERIALIZED_NAME_INGRESS)
  private List<String> ingress = null;

  public static final String SERIALIZED_NAME_REGISTRY = "registry";
  @SerializedName(SERIALIZED_NAME_REGISTRY)
  private List<String> registry = null;


  public V1beta1TrainingPortalStatusEducatesSecrets ingress(List<String> ingress) {
    
    this.ingress = ingress;
    return this;
  }

  public V1beta1TrainingPortalStatusEducatesSecrets addIngressItem(String ingressItem) {
    if (this.ingress == null) {
      this.ingress = new ArrayList<>();
    }
    this.ingress.add(ingressItem);
    return this;
  }

   /**
   * Get ingress
   * @return ingress
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getIngress() {
    return ingress;
  }


  public void setIngress(List<String> ingress) {
    this.ingress = ingress;
  }


  public V1beta1TrainingPortalStatusEducatesSecrets registry(List<String> registry) {
    
    this.registry = registry;
    return this;
  }

  public V1beta1TrainingPortalStatusEducatesSecrets addRegistryItem(String registryItem) {
    if (this.registry == null) {
      this.registry = new ArrayList<>();
    }
    this.registry.add(registryItem);
    return this;
  }

   /**
   * Get registry
   * @return registry
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getRegistry() {
    return registry;
  }


  public void setRegistry(List<String> registry) {
    this.registry = registry;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1TrainingPortalStatusEducatesSecrets v1beta1TrainingPortalStatusEducatesSecrets = (V1beta1TrainingPortalStatusEducatesSecrets) o;
    return Objects.equals(this.ingress, v1beta1TrainingPortalStatusEducatesSecrets.ingress) &&
        Objects.equals(this.registry, v1beta1TrainingPortalStatusEducatesSecrets.registry);
  }

  @Override
  public int hashCode() {
    return Objects.hash(ingress, registry);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1TrainingPortalStatusEducatesSecrets {\n");
    sb.append("    ingress: ").append(toIndentedString(ingress)).append("\n");
    sb.append("    registry: ").append(toIndentedString(registry)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

