/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1WorkshopSpecRequestParameters;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1WorkshopSpecRequest
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSpecRequest {
  public static final String SERIALIZED_NAME_OBJECTS = "objects";
  @SerializedName(SERIALIZED_NAME_OBJECTS)
  private List<Object> objects = null;

  public static final String SERIALIZED_NAME_PARAMETERS = "parameters";
  @SerializedName(SERIALIZED_NAME_PARAMETERS)
  private List<V1beta1WorkshopSpecRequestParameters> parameters = null;


  public V1beta1WorkshopSpecRequest objects(List<Object> objects) {
    
    this.objects = objects;
    return this;
  }

  public V1beta1WorkshopSpecRequest addObjectsItem(Object objectsItem) {
    if (this.objects == null) {
      this.objects = new ArrayList<>();
    }
    this.objects.add(objectsItem);
    return this;
  }

   /**
   * Get objects
   * @return objects
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<Object> getObjects() {
    return objects;
  }


  public void setObjects(List<Object> objects) {
    this.objects = objects;
  }


  public V1beta1WorkshopSpecRequest parameters(List<V1beta1WorkshopSpecRequestParameters> parameters) {
    
    this.parameters = parameters;
    return this;
  }

  public V1beta1WorkshopSpecRequest addParametersItem(V1beta1WorkshopSpecRequestParameters parametersItem) {
    if (this.parameters == null) {
      this.parameters = new ArrayList<>();
    }
    this.parameters.add(parametersItem);
    return this;
  }

   /**
   * Get parameters
   * @return parameters
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1WorkshopSpecRequestParameters> getParameters() {
    return parameters;
  }


  public void setParameters(List<V1beta1WorkshopSpecRequestParameters> parameters) {
    this.parameters = parameters;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSpecRequest v1beta1WorkshopSpecRequest = (V1beta1WorkshopSpecRequest) o;
    return Objects.equals(this.objects, v1beta1WorkshopSpecRequest.objects) &&
        Objects.equals(this.parameters, v1beta1WorkshopSpecRequest.parameters);
  }

  @Override
  public int hashCode() {
    return Objects.hash(objects, parameters);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSpecRequest {\n");
    sb.append("    objects: ").append(toIndentedString(objects)).append("\n");
    sb.append("    parameters: ").append(toIndentedString(parameters)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

