/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1TrainingPortalSpecPortalLabels;
import dev.educates.training.V1beta1WorkshopEnvironmentSpecSessionIngress;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1WorkshopEnvironmentSpecSession
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopEnvironmentSpecSession {
  public static final String SERIALIZED_NAME_ENV = "env";
  @SerializedName(SERIALIZED_NAME_ENV)
  private List<V1beta1TrainingPortalSpecPortalLabels> env = null;

  public static final String SERIALIZED_NAME_INGRESS = "ingress";
  @SerializedName(SERIALIZED_NAME_INGRESS)
  private V1beta1WorkshopEnvironmentSpecSessionIngress ingress;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_USERNAME = "username";
  @SerializedName(SERIALIZED_NAME_USERNAME)
  private String username;


  public V1beta1WorkshopEnvironmentSpecSession env(List<V1beta1TrainingPortalSpecPortalLabels> env) {
    
    this.env = env;
    return this;
  }

  public V1beta1WorkshopEnvironmentSpecSession addEnvItem(V1beta1TrainingPortalSpecPortalLabels envItem) {
    if (this.env == null) {
      this.env = new ArrayList<>();
    }
    this.env.add(envItem);
    return this;
  }

   /**
   * Get env
   * @return env
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1TrainingPortalSpecPortalLabels> getEnv() {
    return env;
  }


  public void setEnv(List<V1beta1TrainingPortalSpecPortalLabels> env) {
    this.env = env;
  }


  public V1beta1WorkshopEnvironmentSpecSession ingress(V1beta1WorkshopEnvironmentSpecSessionIngress ingress) {
    
    this.ingress = ingress;
    return this;
  }

   /**
   * Get ingress
   * @return ingress
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopEnvironmentSpecSessionIngress getIngress() {
    return ingress;
  }


  public void setIngress(V1beta1WorkshopEnvironmentSpecSessionIngress ingress) {
    this.ingress = ingress;
  }


  public V1beta1WorkshopEnvironmentSpecSession password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  public V1beta1WorkshopEnvironmentSpecSession username(String username) {
    
    this.username = username;
    return this;
  }

   /**
   * Get username
   * @return username
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUsername() {
    return username;
  }


  public void setUsername(String username) {
    this.username = username;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopEnvironmentSpecSession v1beta1WorkshopEnvironmentSpecSession = (V1beta1WorkshopEnvironmentSpecSession) o;
    return Objects.equals(this.env, v1beta1WorkshopEnvironmentSpecSession.env) &&
        Objects.equals(this.ingress, v1beta1WorkshopEnvironmentSpecSession.ingress) &&
        Objects.equals(this.password, v1beta1WorkshopEnvironmentSpecSession.password) &&
        Objects.equals(this.username, v1beta1WorkshopEnvironmentSpecSession.username);
  }

  @Override
  public int hashCode() {
    return Objects.hash(env, ingress, password, username);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopEnvironmentSpecSession {\n");
    sb.append("    env: ").append(toIndentedString(env)).append("\n");
    sb.append("    ingress: ").append(toIndentedString(ingress)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    username: ").append(toIndentedString(username)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

