/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1TrainingPortalSpecPortalThemeFrame;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1TrainingPortalSpecPortalTheme
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1TrainingPortalSpecPortalTheme {
  public static final String SERIALIZED_NAME_FRAME = "frame";
  @SerializedName(SERIALIZED_NAME_FRAME)
  private V1beta1TrainingPortalSpecPortalThemeFrame frame;

  public static final String SERIALIZED_NAME_NAME = "name";
  @SerializedName(SERIALIZED_NAME_NAME)
  private String name;


  public V1beta1TrainingPortalSpecPortalTheme frame(V1beta1TrainingPortalSpecPortalThemeFrame frame) {
    
    this.frame = frame;
    return this;
  }

   /**
   * Get frame
   * @return frame
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalThemeFrame getFrame() {
    return frame;
  }


  public void setFrame(V1beta1TrainingPortalSpecPortalThemeFrame frame) {
    this.frame = frame;
  }


  public V1beta1TrainingPortalSpecPortalTheme name(String name) {
    
    this.name = name;
    return this;
  }

   /**
   * Get name
   * @return name
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getName() {
    return name;
  }


  public void setName(String name) {
    this.name = name;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1TrainingPortalSpecPortalTheme v1beta1TrainingPortalSpecPortalTheme = (V1beta1TrainingPortalSpecPortalTheme) o;
    return Objects.equals(this.frame, v1beta1TrainingPortalSpecPortalTheme.frame) &&
        Objects.equals(this.name, v1beta1TrainingPortalSpecPortalTheme.name);
  }

  @Override
  public int hashCode() {
    return Objects.hash(frame, name);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1TrainingPortalSpecPortalTheme {\n");
    sb.append("    frame: ").append(toIndentedString(frame)).append("\n");
    sb.append("    name: ").append(toIndentedString(name)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

