/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1TrainingPortalSpecPortalCookies;
import dev.educates.training.V1beta1TrainingPortalSpecPortalWorkshopDefaultsRegistry;
import dev.educates.training.V1beta1WorkshopAllocationSpecEnvironment;
import dev.educates.training.V1beta1WorkshopEnvironmentSpecEnvironment;
import dev.educates.training.V1beta1WorkshopEnvironmentSpecRequest;
import dev.educates.training.V1beta1WorkshopEnvironmentSpecSession;
import dev.educates.training.V1beta1WorkshopEnvironmentSpecTheme;
import dev.educates.training.V1beta1WorkshopSessionSpecAnalytics;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1WorkshopEnvironmentSpec
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopEnvironmentSpec {
  public static final String SERIALIZED_NAME_ANALYTICS = "analytics";
  @SerializedName(SERIALIZED_NAME_ANALYTICS)
  private V1beta1WorkshopSessionSpecAnalytics analytics;

  public static final String SERIALIZED_NAME_COOKIES = "cookies";
  @SerializedName(SERIALIZED_NAME_COOKIES)
  private V1beta1TrainingPortalSpecPortalCookies cookies;

  public static final String SERIALIZED_NAME_ENVIRONMENT = "environment";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT)
  private V1beta1WorkshopEnvironmentSpecEnvironment environment;

  public static final String SERIALIZED_NAME_REGISTRY = "registry";
  @SerializedName(SERIALIZED_NAME_REGISTRY)
  private V1beta1TrainingPortalSpecPortalWorkshopDefaultsRegistry registry;

  public static final String SERIALIZED_NAME_REQUEST = "request";
  @SerializedName(SERIALIZED_NAME_REQUEST)
  private V1beta1WorkshopEnvironmentSpecRequest request;

  public static final String SERIALIZED_NAME_SESSION = "session";
  @SerializedName(SERIALIZED_NAME_SESSION)
  private V1beta1WorkshopEnvironmentSpecSession session;

  public static final String SERIALIZED_NAME_THEME = "theme";
  @SerializedName(SERIALIZED_NAME_THEME)
  private V1beta1WorkshopEnvironmentSpecTheme theme;

  public static final String SERIALIZED_NAME_WORKSHOP = "workshop";
  @SerializedName(SERIALIZED_NAME_WORKSHOP)
  private V1beta1WorkshopAllocationSpecEnvironment workshop;


  public V1beta1WorkshopEnvironmentSpec analytics(V1beta1WorkshopSessionSpecAnalytics analytics) {
    
    this.analytics = analytics;
    return this;
  }

   /**
   * Get analytics
   * @return analytics
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSessionSpecAnalytics getAnalytics() {
    return analytics;
  }


  public void setAnalytics(V1beta1WorkshopSessionSpecAnalytics analytics) {
    this.analytics = analytics;
  }


  public V1beta1WorkshopEnvironmentSpec cookies(V1beta1TrainingPortalSpecPortalCookies cookies) {
    
    this.cookies = cookies;
    return this;
  }

   /**
   * Get cookies
   * @return cookies
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalCookies getCookies() {
    return cookies;
  }


  public void setCookies(V1beta1TrainingPortalSpecPortalCookies cookies) {
    this.cookies = cookies;
  }


  public V1beta1WorkshopEnvironmentSpec environment(V1beta1WorkshopEnvironmentSpecEnvironment environment) {
    
    this.environment = environment;
    return this;
  }

   /**
   * Get environment
   * @return environment
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopEnvironmentSpecEnvironment getEnvironment() {
    return environment;
  }


  public void setEnvironment(V1beta1WorkshopEnvironmentSpecEnvironment environment) {
    this.environment = environment;
  }


  public V1beta1WorkshopEnvironmentSpec registry(V1beta1TrainingPortalSpecPortalWorkshopDefaultsRegistry registry) {
    
    this.registry = registry;
    return this;
  }

   /**
   * Get registry
   * @return registry
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalWorkshopDefaultsRegistry getRegistry() {
    return registry;
  }


  public void setRegistry(V1beta1TrainingPortalSpecPortalWorkshopDefaultsRegistry registry) {
    this.registry = registry;
  }


  public V1beta1WorkshopEnvironmentSpec request(V1beta1WorkshopEnvironmentSpecRequest request) {
    
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopEnvironmentSpecRequest getRequest() {
    return request;
  }


  public void setRequest(V1beta1WorkshopEnvironmentSpecRequest request) {
    this.request = request;
  }


  public V1beta1WorkshopEnvironmentSpec session(V1beta1WorkshopEnvironmentSpecSession session) {
    
    this.session = session;
    return this;
  }

   /**
   * Get session
   * @return session
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopEnvironmentSpecSession getSession() {
    return session;
  }


  public void setSession(V1beta1WorkshopEnvironmentSpecSession session) {
    this.session = session;
  }


  public V1beta1WorkshopEnvironmentSpec theme(V1beta1WorkshopEnvironmentSpecTheme theme) {
    
    this.theme = theme;
    return this;
  }

   /**
   * Get theme
   * @return theme
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopEnvironmentSpecTheme getTheme() {
    return theme;
  }


  public void setTheme(V1beta1WorkshopEnvironmentSpecTheme theme) {
    this.theme = theme;
  }


  public V1beta1WorkshopEnvironmentSpec workshop(V1beta1WorkshopAllocationSpecEnvironment workshop) {
    
    this.workshop = workshop;
    return this;
  }

   /**
   * Get workshop
   * @return workshop
  **/
  @ApiModelProperty(required = true, value = "")

  public V1beta1WorkshopAllocationSpecEnvironment getWorkshop() {
    return workshop;
  }


  public void setWorkshop(V1beta1WorkshopAllocationSpecEnvironment workshop) {
    this.workshop = workshop;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopEnvironmentSpec v1beta1WorkshopEnvironmentSpec = (V1beta1WorkshopEnvironmentSpec) o;
    return Objects.equals(this.analytics, v1beta1WorkshopEnvironmentSpec.analytics) &&
        Objects.equals(this.cookies, v1beta1WorkshopEnvironmentSpec.cookies) &&
        Objects.equals(this.environment, v1beta1WorkshopEnvironmentSpec.environment) &&
        Objects.equals(this.registry, v1beta1WorkshopEnvironmentSpec.registry) &&
        Objects.equals(this.request, v1beta1WorkshopEnvironmentSpec.request) &&
        Objects.equals(this.session, v1beta1WorkshopEnvironmentSpec.session) &&
        Objects.equals(this.theme, v1beta1WorkshopEnvironmentSpec.theme) &&
        Objects.equals(this.workshop, v1beta1WorkshopEnvironmentSpec.workshop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analytics, cookies, environment, registry, request, session, theme, workshop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopEnvironmentSpec {\n");
    sb.append("    analytics: ").append(toIndentedString(analytics)).append("\n");
    sb.append("    cookies: ").append(toIndentedString(cookies)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    registry: ").append(toIndentedString(registry)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    theme: ").append(toIndentedString(theme)).append("\n");
    sb.append("    workshop: ").append(toIndentedString(workshop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

