/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1TrainingPortalSpecPortalIngressTlsCertificateRef;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1TrainingPortalSpecPortalIngress
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1TrainingPortalSpecPortalIngress {
  public static final String SERIALIZED_NAME_HOSTNAME = "hostname";
  @SerializedName(SERIALIZED_NAME_HOSTNAME)
  private String hostname;

  public static final String SERIALIZED_NAME_TLS_CERTIFICATE_REF = "tlsCertificateRef";
  @SerializedName(SERIALIZED_NAME_TLS_CERTIFICATE_REF)
  private V1beta1TrainingPortalSpecPortalIngressTlsCertificateRef tlsCertificateRef;


  public V1beta1TrainingPortalSpecPortalIngress hostname(String hostname) {
    
    this.hostname = hostname;
    return this;
  }

   /**
   * Get hostname
   * @return hostname
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getHostname() {
    return hostname;
  }


  public void setHostname(String hostname) {
    this.hostname = hostname;
  }


  public V1beta1TrainingPortalSpecPortalIngress tlsCertificateRef(V1beta1TrainingPortalSpecPortalIngressTlsCertificateRef tlsCertificateRef) {
    
    this.tlsCertificateRef = tlsCertificateRef;
    return this;
  }

   /**
   * Get tlsCertificateRef
   * @return tlsCertificateRef
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalIngressTlsCertificateRef getTlsCertificateRef() {
    return tlsCertificateRef;
  }


  public void setTlsCertificateRef(V1beta1TrainingPortalSpecPortalIngressTlsCertificateRef tlsCertificateRef) {
    this.tlsCertificateRef = tlsCertificateRef;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1TrainingPortalSpecPortalIngress v1beta1TrainingPortalSpecPortalIngress = (V1beta1TrainingPortalSpecPortalIngress) o;
    return Objects.equals(this.hostname, v1beta1TrainingPortalSpecPortalIngress.hostname) &&
        Objects.equals(this.tlsCertificateRef, v1beta1TrainingPortalSpecPortalIngress.tlsCertificateRef);
  }

  @Override
  public int hashCode() {
    return Objects.hash(hostname, tlsCertificateRef);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1TrainingPortalSpecPortalIngress {\n");
    sb.append("    hostname: ").append(toIndentedString(hostname)).append("\n");
    sb.append("    tlsCertificateRef: ").append(toIndentedString(tlsCertificateRef)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

