/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1TrainingPortalSpecAnalyticsAmplitude;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1WorkshopSessionSpecAnalytics
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSessionSpecAnalytics {
  public static final String SERIALIZED_NAME_AMPLITUDE = "amplitude";
  @SerializedName(SERIALIZED_NAME_AMPLITUDE)
  private V1beta1TrainingPortalSpecAnalyticsAmplitude amplitude;

  public static final String SERIALIZED_NAME_CLARITY = "clarity";
  @SerializedName(SERIALIZED_NAME_CLARITY)
  private V1beta1TrainingPortalSpecAnalyticsAmplitude clarity;

  public static final String SERIALIZED_NAME_GOOGLE = "google";
  @SerializedName(SERIALIZED_NAME_GOOGLE)
  private V1beta1TrainingPortalSpecAnalyticsAmplitude google;


  public V1beta1WorkshopSessionSpecAnalytics amplitude(V1beta1TrainingPortalSpecAnalyticsAmplitude amplitude) {
    
    this.amplitude = amplitude;
    return this;
  }

   /**
   * Get amplitude
   * @return amplitude
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecAnalyticsAmplitude getAmplitude() {
    return amplitude;
  }


  public void setAmplitude(V1beta1TrainingPortalSpecAnalyticsAmplitude amplitude) {
    this.amplitude = amplitude;
  }


  public V1beta1WorkshopSessionSpecAnalytics clarity(V1beta1TrainingPortalSpecAnalyticsAmplitude clarity) {
    
    this.clarity = clarity;
    return this;
  }

   /**
   * Get clarity
   * @return clarity
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecAnalyticsAmplitude getClarity() {
    return clarity;
  }


  public void setClarity(V1beta1TrainingPortalSpecAnalyticsAmplitude clarity) {
    this.clarity = clarity;
  }


  public V1beta1WorkshopSessionSpecAnalytics google(V1beta1TrainingPortalSpecAnalyticsAmplitude google) {
    
    this.google = google;
    return this;
  }

   /**
   * Get google
   * @return google
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecAnalyticsAmplitude getGoogle() {
    return google;
  }


  public void setGoogle(V1beta1TrainingPortalSpecAnalyticsAmplitude google) {
    this.google = google;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSessionSpecAnalytics v1beta1WorkshopSessionSpecAnalytics = (V1beta1WorkshopSessionSpecAnalytics) o;
    return Objects.equals(this.amplitude, v1beta1WorkshopSessionSpecAnalytics.amplitude) &&
        Objects.equals(this.clarity, v1beta1WorkshopSessionSpecAnalytics.clarity) &&
        Objects.equals(this.google, v1beta1WorkshopSessionSpecAnalytics.google);
  }

  @Override
  public int hashCode() {
    return Objects.hash(amplitude, clarity, google);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSessionSpecAnalytics {\n");
    sb.append("    amplitude: ").append(toIndentedString(amplitude)).append("\n");
    sb.append("    clarity: ").append(toIndentedString(clarity)).append("\n");
    sb.append("    google: ").append(toIndentedString(google)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

