/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1WorkshopSpecSessionApplicationsWorkshopProxy;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1WorkshopSpecSessionApplicationsWorkshop
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSpecSessionApplicationsWorkshop {
  public static final String SERIALIZED_NAME_ENABLED = "enabled";
  @SerializedName(SERIALIZED_NAME_ENABLED)
  private Boolean enabled;

  public static final String SERIALIZED_NAME_LAYOUT = "layout";
  @SerializedName(SERIALIZED_NAME_LAYOUT)
  private String layout;

  public static final String SERIALIZED_NAME_PATH = "path";
  @SerializedName(SERIALIZED_NAME_PATH)
  private String path;

  public static final String SERIALIZED_NAME_PROXY = "proxy";
  @SerializedName(SERIALIZED_NAME_PROXY)
  private V1beta1WorkshopSpecSessionApplicationsWorkshopProxy proxy;

  /**
   * Gets or Sets renderer
   */
  @JsonAdapter(RendererEnum.Adapter.class)
  public enum RendererEnum {
    LOCAL("local"),
    
    REMOTE("remote"),
    
    STATIC("static"),
    
    PROXY("proxy");

    private String value;

    RendererEnum(String value) {
      this.value = value;
    }

    public String getValue() {
      return value;
    }

    @Override
    public String toString() {
      return String.valueOf(value);
    }

    public static RendererEnum fromValue(String value) {
      for (RendererEnum b : RendererEnum.values()) {
        if (b.value.equals(value)) {
          return b;
        }
      }
      throw new IllegalArgumentException("Unexpected value '" + value + "'");
    }

    public static class Adapter extends TypeAdapter<RendererEnum> {
      @Override
      public void write(final JsonWriter jsonWriter, final RendererEnum enumeration) throws IOException {
        jsonWriter.value(enumeration.getValue());
      }

      @Override
      public RendererEnum read(final JsonReader jsonReader) throws IOException {
        String value =  jsonReader.nextString();
        return RendererEnum.fromValue(value);
      }
    }
  }

  public static final String SERIALIZED_NAME_RENDERER = "renderer";
  @SerializedName(SERIALIZED_NAME_RENDERER)
  private RendererEnum renderer;

  public static final String SERIALIZED_NAME_URL = "url";
  @SerializedName(SERIALIZED_NAME_URL)
  private String url;


  public V1beta1WorkshopSpecSessionApplicationsWorkshop enabled(Boolean enabled) {
    
    this.enabled = enabled;
    return this;
  }

   /**
   * Get enabled
   * @return enabled
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getEnabled() {
    return enabled;
  }


  public void setEnabled(Boolean enabled) {
    this.enabled = enabled;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshop layout(String layout) {
    
    this.layout = layout;
    return this;
  }

   /**
   * Get layout
   * @return layout
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLayout() {
    return layout;
  }


  public void setLayout(String layout) {
    this.layout = layout;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshop path(String path) {
    
    this.path = path;
    return this;
  }

   /**
   * Get path
   * @return path
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPath() {
    return path;
  }


  public void setPath(String path) {
    this.path = path;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshop proxy(V1beta1WorkshopSpecSessionApplicationsWorkshopProxy proxy) {
    
    this.proxy = proxy;
    return this;
  }

   /**
   * Get proxy
   * @return proxy
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsWorkshopProxy getProxy() {
    return proxy;
  }


  public void setProxy(V1beta1WorkshopSpecSessionApplicationsWorkshopProxy proxy) {
    this.proxy = proxy;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshop renderer(RendererEnum renderer) {
    
    this.renderer = renderer;
    return this;
  }

   /**
   * Get renderer
   * @return renderer
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public RendererEnum getRenderer() {
    return renderer;
  }


  public void setRenderer(RendererEnum renderer) {
    this.renderer = renderer;
  }


  public V1beta1WorkshopSpecSessionApplicationsWorkshop url(String url) {
    
    this.url = url;
    return this;
  }

   /**
   * Get url
   * @return url
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getUrl() {
    return url;
  }


  public void setUrl(String url) {
    this.url = url;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSpecSessionApplicationsWorkshop v1beta1WorkshopSpecSessionApplicationsWorkshop = (V1beta1WorkshopSpecSessionApplicationsWorkshop) o;
    return Objects.equals(this.enabled, v1beta1WorkshopSpecSessionApplicationsWorkshop.enabled) &&
        Objects.equals(this.layout, v1beta1WorkshopSpecSessionApplicationsWorkshop.layout) &&
        Objects.equals(this.path, v1beta1WorkshopSpecSessionApplicationsWorkshop.path) &&
        Objects.equals(this.proxy, v1beta1WorkshopSpecSessionApplicationsWorkshop.proxy) &&
        Objects.equals(this.renderer, v1beta1WorkshopSpecSessionApplicationsWorkshop.renderer) &&
        Objects.equals(this.url, v1beta1WorkshopSpecSessionApplicationsWorkshop.url);
  }

  @Override
  public int hashCode() {
    return Objects.hash(enabled, layout, path, proxy, renderer, url);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSpecSessionApplicationsWorkshop {\n");
    sb.append("    enabled: ").append(toIndentedString(enabled)).append("\n");
    sb.append("    layout: ").append(toIndentedString(layout)).append("\n");
    sb.append("    path: ").append(toIndentedString(path)).append("\n");
    sb.append("    proxy: ").append(toIndentedString(proxy)).append("\n");
    sb.append("    renderer: ").append(toIndentedString(renderer)).append("\n");
    sb.append("    url: ").append(toIndentedString(url)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

