/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1TrainingPortalSpecAnalytics;
import dev.educates.training.V1beta1TrainingPortalSpecPortal;
import dev.educates.training.V1beta1TrainingPortalSpecWorkshops;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1TrainingPortalSpec
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1TrainingPortalSpec {
  public static final String SERIALIZED_NAME_ANALYTICS = "analytics";
  @SerializedName(SERIALIZED_NAME_ANALYTICS)
  private V1beta1TrainingPortalSpecAnalytics analytics;

  public static final String SERIALIZED_NAME_PORTAL = "portal";
  @SerializedName(SERIALIZED_NAME_PORTAL)
  private V1beta1TrainingPortalSpecPortal portal;

  public static final String SERIALIZED_NAME_WORKSHOPS = "workshops";
  @SerializedName(SERIALIZED_NAME_WORKSHOPS)
  private List<V1beta1TrainingPortalSpecWorkshops> workshops = null;


  public V1beta1TrainingPortalSpec analytics(V1beta1TrainingPortalSpecAnalytics analytics) {
    
    this.analytics = analytics;
    return this;
  }

   /**
   * Get analytics
   * @return analytics
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecAnalytics getAnalytics() {
    return analytics;
  }


  public void setAnalytics(V1beta1TrainingPortalSpecAnalytics analytics) {
    this.analytics = analytics;
  }


  public V1beta1TrainingPortalSpec portal(V1beta1TrainingPortalSpecPortal portal) {
    
    this.portal = portal;
    return this;
  }

   /**
   * Get portal
   * @return portal
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortal getPortal() {
    return portal;
  }


  public void setPortal(V1beta1TrainingPortalSpecPortal portal) {
    this.portal = portal;
  }


  public V1beta1TrainingPortalSpec workshops(List<V1beta1TrainingPortalSpecWorkshops> workshops) {
    
    this.workshops = workshops;
    return this;
  }

  public V1beta1TrainingPortalSpec addWorkshopsItem(V1beta1TrainingPortalSpecWorkshops workshopsItem) {
    if (this.workshops == null) {
      this.workshops = new ArrayList<>();
    }
    this.workshops.add(workshopsItem);
    return this;
  }

   /**
   * Get workshops
   * @return workshops
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1TrainingPortalSpecWorkshops> getWorkshops() {
    return workshops;
  }


  public void setWorkshops(List<V1beta1TrainingPortalSpecWorkshops> workshops) {
    this.workshops = workshops;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1TrainingPortalSpec v1beta1TrainingPortalSpec = (V1beta1TrainingPortalSpec) o;
    return Objects.equals(this.analytics, v1beta1TrainingPortalSpec.analytics) &&
        Objects.equals(this.portal, v1beta1TrainingPortalSpec.portal) &&
        Objects.equals(this.workshops, v1beta1TrainingPortalSpec.workshops);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analytics, portal, workshops);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1TrainingPortalSpec {\n");
    sb.append("    analytics: ").append(toIndentedString(analytics)).append("\n");
    sb.append("    portal: ").append(toIndentedString(portal)).append("\n");
    sb.append("    workshops: ").append(toIndentedString(workshops)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

