/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1WorkshopSpecEnvironmentAssetsFiles;
import dev.educates.training.V1beta1WorkshopSpecWorkshopPackages;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1WorkshopSpecWorkshop
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSpecWorkshop {
  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private List<V1beta1WorkshopSpecEnvironmentAssetsFiles> files = null;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;

  public static final String SERIALIZED_NAME_PACKAGES = "packages";
  @SerializedName(SERIALIZED_NAME_PACKAGES)
  private List<V1beta1WorkshopSpecWorkshopPackages> packages = null;


  public V1beta1WorkshopSpecWorkshop files(List<V1beta1WorkshopSpecEnvironmentAssetsFiles> files) {
    
    this.files = files;
    return this;
  }

  public V1beta1WorkshopSpecWorkshop addFilesItem(V1beta1WorkshopSpecEnvironmentAssetsFiles filesItem) {
    if (this.files == null) {
      this.files = new ArrayList<>();
    }
    this.files.add(filesItem);
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1WorkshopSpecEnvironmentAssetsFiles> getFiles() {
    return files;
  }


  public void setFiles(List<V1beta1WorkshopSpecEnvironmentAssetsFiles> files) {
    this.files = files;
  }


  public V1beta1WorkshopSpecWorkshop image(String image) {
    
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImage() {
    return image;
  }


  public void setImage(String image) {
    this.image = image;
  }


  public V1beta1WorkshopSpecWorkshop packages(List<V1beta1WorkshopSpecWorkshopPackages> packages) {
    
    this.packages = packages;
    return this;
  }

  public V1beta1WorkshopSpecWorkshop addPackagesItem(V1beta1WorkshopSpecWorkshopPackages packagesItem) {
    if (this.packages == null) {
      this.packages = new ArrayList<>();
    }
    this.packages.add(packagesItem);
    return this;
  }

   /**
   * Get packages
   * @return packages
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1WorkshopSpecWorkshopPackages> getPackages() {
    return packages;
  }


  public void setPackages(List<V1beta1WorkshopSpecWorkshopPackages> packages) {
    this.packages = packages;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSpecWorkshop v1beta1WorkshopSpecWorkshop = (V1beta1WorkshopSpecWorkshop) o;
    return Objects.equals(this.files, v1beta1WorkshopSpecWorkshop.files) &&
        Objects.equals(this.image, v1beta1WorkshopSpecWorkshop.image) &&
        Objects.equals(this.packages, v1beta1WorkshopSpecWorkshop.packages);
  }

  @Override
  public int hashCode() {
    return Objects.hash(files, image, packages);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSpecWorkshop {\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("    packages: ").append(toIndentedString(packages)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

