/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1TrainingPortalSpecPortalCatalog;
import dev.educates.training.V1beta1TrainingPortalSpecPortalClients;
import dev.educates.training.V1beta1TrainingPortalSpecPortalCookies;
import dev.educates.training.V1beta1TrainingPortalSpecPortalCredentials;
import dev.educates.training.V1beta1TrainingPortalSpecPortalIngress;
import dev.educates.training.V1beta1TrainingPortalSpecPortalLabels;
import dev.educates.training.V1beta1TrainingPortalSpecPortalRegistration;
import dev.educates.training.V1beta1TrainingPortalSpecPortalSessions;
import dev.educates.training.V1beta1TrainingPortalSpecPortalTheme;
import dev.educates.training.V1beta1TrainingPortalSpecPortalUpdates;
import dev.educates.training.V1beta1TrainingPortalSpecPortalWorkshop;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1TrainingPortalSpecPortal
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1TrainingPortalSpecPortal {
  public static final String SERIALIZED_NAME_CAPACITY = "capacity";
  @SerializedName(SERIALIZED_NAME_CAPACITY)
  private Integer capacity;

  public static final String SERIALIZED_NAME_CATALOG = "catalog";
  @SerializedName(SERIALIZED_NAME_CATALOG)
  private V1beta1TrainingPortalSpecPortalCatalog catalog;

  public static final String SERIALIZED_NAME_CLIENTS = "clients";
  @SerializedName(SERIALIZED_NAME_CLIENTS)
  private V1beta1TrainingPortalSpecPortalClients clients;

  public static final String SERIALIZED_NAME_COOKIES = "cookies";
  @SerializedName(SERIALIZED_NAME_COOKIES)
  private V1beta1TrainingPortalSpecPortalCookies cookies;

  public static final String SERIALIZED_NAME_CREDENTIALS = "credentials";
  @SerializedName(SERIALIZED_NAME_CREDENTIALS)
  private V1beta1TrainingPortalSpecPortalCredentials credentials;

  public static final String SERIALIZED_NAME_EXPIRES = "expires";
  @SerializedName(SERIALIZED_NAME_EXPIRES)
  private String expires;

  public static final String SERIALIZED_NAME_INDEX = "index";
  @SerializedName(SERIALIZED_NAME_INDEX)
  private String index;

  public static final String SERIALIZED_NAME_INGRESS = "ingress";
  @SerializedName(SERIALIZED_NAME_INGRESS)
  private V1beta1TrainingPortalSpecPortalIngress ingress;

  public static final String SERIALIZED_NAME_INITIAL = "initial";
  @SerializedName(SERIALIZED_NAME_INITIAL)
  private Integer initial;

  public static final String SERIALIZED_NAME_LABELS = "labels";
  @SerializedName(SERIALIZED_NAME_LABELS)
  private List<V1beta1TrainingPortalSpecPortalLabels> labels = null;

  public static final String SERIALIZED_NAME_LOGO = "logo";
  @SerializedName(SERIALIZED_NAME_LOGO)
  private String logo;

  public static final String SERIALIZED_NAME_ORPHANED = "orphaned";
  @SerializedName(SERIALIZED_NAME_ORPHANED)
  private String orphaned;

  public static final String SERIALIZED_NAME_PASSWORD = "password";
  @SerializedName(SERIALIZED_NAME_PASSWORD)
  private String password;

  public static final String SERIALIZED_NAME_REGISTRATION = "registration";
  @SerializedName(SERIALIZED_NAME_REGISTRATION)
  private V1beta1TrainingPortalSpecPortalRegistration registration;

  public static final String SERIALIZED_NAME_RESERVED = "reserved";
  @SerializedName(SERIALIZED_NAME_RESERVED)
  private Integer reserved;

  public static final String SERIALIZED_NAME_SESSIONS = "sessions";
  @SerializedName(SERIALIZED_NAME_SESSIONS)
  private V1beta1TrainingPortalSpecPortalSessions sessions;

  public static final String SERIALIZED_NAME_THEME = "theme";
  @SerializedName(SERIALIZED_NAME_THEME)
  private V1beta1TrainingPortalSpecPortalTheme theme;

  public static final String SERIALIZED_NAME_TITLE = "title";
  @SerializedName(SERIALIZED_NAME_TITLE)
  private String title;

  public static final String SERIALIZED_NAME_UPDATES = "updates";
  @SerializedName(SERIALIZED_NAME_UPDATES)
  private V1beta1TrainingPortalSpecPortalUpdates updates;

  public static final String SERIALIZED_NAME_WORKSHOP = "workshop";
  @SerializedName(SERIALIZED_NAME_WORKSHOP)
  private V1beta1TrainingPortalSpecPortalWorkshop workshop;


  public V1beta1TrainingPortalSpecPortal capacity(Integer capacity) {
    
    this.capacity = capacity;
    return this;
  }

   /**
   * Get capacity
   * @return capacity
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getCapacity() {
    return capacity;
  }


  public void setCapacity(Integer capacity) {
    this.capacity = capacity;
  }


  public V1beta1TrainingPortalSpecPortal catalog(V1beta1TrainingPortalSpecPortalCatalog catalog) {
    
    this.catalog = catalog;
    return this;
  }

   /**
   * Get catalog
   * @return catalog
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalCatalog getCatalog() {
    return catalog;
  }


  public void setCatalog(V1beta1TrainingPortalSpecPortalCatalog catalog) {
    this.catalog = catalog;
  }


  public V1beta1TrainingPortalSpecPortal clients(V1beta1TrainingPortalSpecPortalClients clients) {
    
    this.clients = clients;
    return this;
  }

   /**
   * Get clients
   * @return clients
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalClients getClients() {
    return clients;
  }


  public void setClients(V1beta1TrainingPortalSpecPortalClients clients) {
    this.clients = clients;
  }


  public V1beta1TrainingPortalSpecPortal cookies(V1beta1TrainingPortalSpecPortalCookies cookies) {
    
    this.cookies = cookies;
    return this;
  }

   /**
   * Get cookies
   * @return cookies
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalCookies getCookies() {
    return cookies;
  }


  public void setCookies(V1beta1TrainingPortalSpecPortalCookies cookies) {
    this.cookies = cookies;
  }


  public V1beta1TrainingPortalSpecPortal credentials(V1beta1TrainingPortalSpecPortalCredentials credentials) {
    
    this.credentials = credentials;
    return this;
  }

   /**
   * Get credentials
   * @return credentials
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalCredentials getCredentials() {
    return credentials;
  }


  public void setCredentials(V1beta1TrainingPortalSpecPortalCredentials credentials) {
    this.credentials = credentials;
  }


  public V1beta1TrainingPortalSpecPortal expires(String expires) {
    
    this.expires = expires;
    return this;
  }

   /**
   * Get expires
   * @return expires
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getExpires() {
    return expires;
  }


  public void setExpires(String expires) {
    this.expires = expires;
  }


  public V1beta1TrainingPortalSpecPortal index(String index) {
    
    this.index = index;
    return this;
  }

   /**
   * Get index
   * @return index
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getIndex() {
    return index;
  }


  public void setIndex(String index) {
    this.index = index;
  }


  public V1beta1TrainingPortalSpecPortal ingress(V1beta1TrainingPortalSpecPortalIngress ingress) {
    
    this.ingress = ingress;
    return this;
  }

   /**
   * Get ingress
   * @return ingress
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalIngress getIngress() {
    return ingress;
  }


  public void setIngress(V1beta1TrainingPortalSpecPortalIngress ingress) {
    this.ingress = ingress;
  }


  public V1beta1TrainingPortalSpecPortal initial(Integer initial) {
    
    this.initial = initial;
    return this;
  }

   /**
   * Get initial
   * @return initial
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getInitial() {
    return initial;
  }


  public void setInitial(Integer initial) {
    this.initial = initial;
  }


  public V1beta1TrainingPortalSpecPortal labels(List<V1beta1TrainingPortalSpecPortalLabels> labels) {
    
    this.labels = labels;
    return this;
  }

  public V1beta1TrainingPortalSpecPortal addLabelsItem(V1beta1TrainingPortalSpecPortalLabels labelsItem) {
    if (this.labels == null) {
      this.labels = new ArrayList<>();
    }
    this.labels.add(labelsItem);
    return this;
  }

   /**
   * Get labels
   * @return labels
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<V1beta1TrainingPortalSpecPortalLabels> getLabels() {
    return labels;
  }


  public void setLabels(List<V1beta1TrainingPortalSpecPortalLabels> labels) {
    this.labels = labels;
  }


  public V1beta1TrainingPortalSpecPortal logo(String logo) {
    
    this.logo = logo;
    return this;
  }

   /**
   * Get logo
   * @return logo
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getLogo() {
    return logo;
  }


  public void setLogo(String logo) {
    this.logo = logo;
  }


  public V1beta1TrainingPortalSpecPortal orphaned(String orphaned) {
    
    this.orphaned = orphaned;
    return this;
  }

   /**
   * Get orphaned
   * @return orphaned
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getOrphaned() {
    return orphaned;
  }


  public void setOrphaned(String orphaned) {
    this.orphaned = orphaned;
  }


  public V1beta1TrainingPortalSpecPortal password(String password) {
    
    this.password = password;
    return this;
  }

   /**
   * Get password
   * @return password
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getPassword() {
    return password;
  }


  public void setPassword(String password) {
    this.password = password;
  }


  public V1beta1TrainingPortalSpecPortal registration(V1beta1TrainingPortalSpecPortalRegistration registration) {
    
    this.registration = registration;
    return this;
  }

   /**
   * Get registration
   * @return registration
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalRegistration getRegistration() {
    return registration;
  }


  public void setRegistration(V1beta1TrainingPortalSpecPortalRegistration registration) {
    this.registration = registration;
  }


  public V1beta1TrainingPortalSpecPortal reserved(Integer reserved) {
    
    this.reserved = reserved;
    return this;
  }

   /**
   * Get reserved
   * @return reserved
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getReserved() {
    return reserved;
  }


  public void setReserved(Integer reserved) {
    this.reserved = reserved;
  }


  public V1beta1TrainingPortalSpecPortal sessions(V1beta1TrainingPortalSpecPortalSessions sessions) {
    
    this.sessions = sessions;
    return this;
  }

   /**
   * Get sessions
   * @return sessions
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalSessions getSessions() {
    return sessions;
  }


  public void setSessions(V1beta1TrainingPortalSpecPortalSessions sessions) {
    this.sessions = sessions;
  }


  public V1beta1TrainingPortalSpecPortal theme(V1beta1TrainingPortalSpecPortalTheme theme) {
    
    this.theme = theme;
    return this;
  }

   /**
   * Get theme
   * @return theme
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalTheme getTheme() {
    return theme;
  }


  public void setTheme(V1beta1TrainingPortalSpecPortalTheme theme) {
    this.theme = theme;
  }


  public V1beta1TrainingPortalSpecPortal title(String title) {
    
    this.title = title;
    return this;
  }

   /**
   * Get title
   * @return title
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getTitle() {
    return title;
  }


  public void setTitle(String title) {
    this.title = title;
  }


  public V1beta1TrainingPortalSpecPortal updates(V1beta1TrainingPortalSpecPortalUpdates updates) {
    
    this.updates = updates;
    return this;
  }

   /**
   * Get updates
   * @return updates
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalUpdates getUpdates() {
    return updates;
  }


  public void setUpdates(V1beta1TrainingPortalSpecPortalUpdates updates) {
    this.updates = updates;
  }


  public V1beta1TrainingPortalSpecPortal workshop(V1beta1TrainingPortalSpecPortalWorkshop workshop) {
    
    this.workshop = workshop;
    return this;
  }

   /**
   * Get workshop
   * @return workshop
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalWorkshop getWorkshop() {
    return workshop;
  }


  public void setWorkshop(V1beta1TrainingPortalSpecPortalWorkshop workshop) {
    this.workshop = workshop;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1TrainingPortalSpecPortal v1beta1TrainingPortalSpecPortal = (V1beta1TrainingPortalSpecPortal) o;
    return Objects.equals(this.capacity, v1beta1TrainingPortalSpecPortal.capacity) &&
        Objects.equals(this.catalog, v1beta1TrainingPortalSpecPortal.catalog) &&
        Objects.equals(this.clients, v1beta1TrainingPortalSpecPortal.clients) &&
        Objects.equals(this.cookies, v1beta1TrainingPortalSpecPortal.cookies) &&
        Objects.equals(this.credentials, v1beta1TrainingPortalSpecPortal.credentials) &&
        Objects.equals(this.expires, v1beta1TrainingPortalSpecPortal.expires) &&
        Objects.equals(this.index, v1beta1TrainingPortalSpecPortal.index) &&
        Objects.equals(this.ingress, v1beta1TrainingPortalSpecPortal.ingress) &&
        Objects.equals(this.initial, v1beta1TrainingPortalSpecPortal.initial) &&
        Objects.equals(this.labels, v1beta1TrainingPortalSpecPortal.labels) &&
        Objects.equals(this.logo, v1beta1TrainingPortalSpecPortal.logo) &&
        Objects.equals(this.orphaned, v1beta1TrainingPortalSpecPortal.orphaned) &&
        Objects.equals(this.password, v1beta1TrainingPortalSpecPortal.password) &&
        Objects.equals(this.registration, v1beta1TrainingPortalSpecPortal.registration) &&
        Objects.equals(this.reserved, v1beta1TrainingPortalSpecPortal.reserved) &&
        Objects.equals(this.sessions, v1beta1TrainingPortalSpecPortal.sessions) &&
        Objects.equals(this.theme, v1beta1TrainingPortalSpecPortal.theme) &&
        Objects.equals(this.title, v1beta1TrainingPortalSpecPortal.title) &&
        Objects.equals(this.updates, v1beta1TrainingPortalSpecPortal.updates) &&
        Objects.equals(this.workshop, v1beta1TrainingPortalSpecPortal.workshop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(capacity, catalog, clients, cookies, credentials, expires, index, ingress, initial, labels, logo, orphaned, password, registration, reserved, sessions, theme, title, updates, workshop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1TrainingPortalSpecPortal {\n");
    sb.append("    capacity: ").append(toIndentedString(capacity)).append("\n");
    sb.append("    catalog: ").append(toIndentedString(catalog)).append("\n");
    sb.append("    clients: ").append(toIndentedString(clients)).append("\n");
    sb.append("    cookies: ").append(toIndentedString(cookies)).append("\n");
    sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
    sb.append("    expires: ").append(toIndentedString(expires)).append("\n");
    sb.append("    index: ").append(toIndentedString(index)).append("\n");
    sb.append("    ingress: ").append(toIndentedString(ingress)).append("\n");
    sb.append("    initial: ").append(toIndentedString(initial)).append("\n");
    sb.append("    labels: ").append(toIndentedString(labels)).append("\n");
    sb.append("    logo: ").append(toIndentedString(logo)).append("\n");
    sb.append("    orphaned: ").append(toIndentedString(orphaned)).append("\n");
    sb.append("    password: ").append(toIndentedString(password)).append("\n");
    sb.append("    registration: ").append(toIndentedString(registration)).append("\n");
    sb.append("    reserved: ").append(toIndentedString(reserved)).append("\n");
    sb.append("    sessions: ").append(toIndentedString(sessions)).append("\n");
    sb.append("    theme: ").append(toIndentedString(theme)).append("\n");
    sb.append("    title: ").append(toIndentedString(title)).append("\n");
    sb.append("    updates: ").append(toIndentedString(updates)).append("\n");
    sb.append("    workshop: ").append(toIndentedString(workshop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

