/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;

import dev.educates.training.V1beta1WorkshopAllocationSpecEnvironment;
import dev.educates.training.V1beta1WorkshopSessionSpecAnalytics;
import dev.educates.training.V1beta1WorkshopSessionSpecPortal;
import dev.educates.training.V1beta1WorkshopSessionSpecRequest;
import dev.educates.training.V1beta1WorkshopSessionSpecSession;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1WorkshopSessionSpec
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSessionSpec {
  public static final String SERIALIZED_NAME_ANALYTICS = "analytics";
  @SerializedName(SERIALIZED_NAME_ANALYTICS)
  private V1beta1WorkshopSessionSpecAnalytics analytics;

  public static final String SERIALIZED_NAME_ENVIRONMENT = "environment";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT)
  private V1beta1WorkshopAllocationSpecEnvironment environment;

  public static final String SERIALIZED_NAME_PORTAL = "portal";
  @SerializedName(SERIALIZED_NAME_PORTAL)
  private V1beta1WorkshopSessionSpecPortal portal;

  public static final String SERIALIZED_NAME_REQUEST = "request";
  @SerializedName(SERIALIZED_NAME_REQUEST)
  private V1beta1WorkshopSessionSpecRequest request;

  public static final String SERIALIZED_NAME_SESSION = "session";
  @SerializedName(SERIALIZED_NAME_SESSION)
  private V1beta1WorkshopSessionSpecSession session;

  public static final String SERIALIZED_NAME_WORKSHOP = "workshop";
  @SerializedName(SERIALIZED_NAME_WORKSHOP)
  private V1beta1WorkshopAllocationSpecEnvironment workshop;


  public V1beta1WorkshopSessionSpec analytics(V1beta1WorkshopSessionSpecAnalytics analytics) {
    
    this.analytics = analytics;
    return this;
  }

   /**
   * Get analytics
   * @return analytics
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSessionSpecAnalytics getAnalytics() {
    return analytics;
  }


  public void setAnalytics(V1beta1WorkshopSessionSpecAnalytics analytics) {
    this.analytics = analytics;
  }


  public V1beta1WorkshopSessionSpec environment(V1beta1WorkshopAllocationSpecEnvironment environment) {
    
    this.environment = environment;
    return this;
  }

   /**
   * Get environment
   * @return environment
  **/
  @ApiModelProperty(required = true, value = "")

  public V1beta1WorkshopAllocationSpecEnvironment getEnvironment() {
    return environment;
  }


  public void setEnvironment(V1beta1WorkshopAllocationSpecEnvironment environment) {
    this.environment = environment;
  }


  public V1beta1WorkshopSessionSpec portal(V1beta1WorkshopSessionSpecPortal portal) {
    
    this.portal = portal;
    return this;
  }

   /**
   * Get portal
   * @return portal
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSessionSpecPortal getPortal() {
    return portal;
  }


  public void setPortal(V1beta1WorkshopSessionSpecPortal portal) {
    this.portal = portal;
  }


  public V1beta1WorkshopSessionSpec request(V1beta1WorkshopSessionSpecRequest request) {
    
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSessionSpecRequest getRequest() {
    return request;
  }


  public void setRequest(V1beta1WorkshopSessionSpecRequest request) {
    this.request = request;
  }


  public V1beta1WorkshopSessionSpec session(V1beta1WorkshopSessionSpecSession session) {
    
    this.session = session;
    return this;
  }

   /**
   * Get session
   * @return session
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSessionSpecSession getSession() {
    return session;
  }


  public void setSession(V1beta1WorkshopSessionSpecSession session) {
    this.session = session;
  }


  public V1beta1WorkshopSessionSpec workshop(V1beta1WorkshopAllocationSpecEnvironment workshop) {
    
    this.workshop = workshop;
    return this;
  }

   /**
   * Get workshop
   * @return workshop
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopAllocationSpecEnvironment getWorkshop() {
    return workshop;
  }


  public void setWorkshop(V1beta1WorkshopAllocationSpecEnvironment workshop) {
    this.workshop = workshop;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSessionSpec v1beta1WorkshopSessionSpec = (V1beta1WorkshopSessionSpec) o;
    return Objects.equals(this.analytics, v1beta1WorkshopSessionSpec.analytics) &&
        Objects.equals(this.environment, v1beta1WorkshopSessionSpec.environment) &&
        Objects.equals(this.portal, v1beta1WorkshopSessionSpec.portal) &&
        Objects.equals(this.request, v1beta1WorkshopSessionSpec.request) &&
        Objects.equals(this.session, v1beta1WorkshopSessionSpec.session) &&
        Objects.equals(this.workshop, v1beta1WorkshopSessionSpec.workshop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analytics, environment, portal, request, session, workshop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSessionSpec {\n");
    sb.append("    analytics: ").append(toIndentedString(analytics)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    portal: ").append(toIndentedString(portal)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    workshop: ").append(toIndentedString(workshop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

