/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package dev.educates.training;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1WorkshopSpecSessionApplicationsDockerCompose
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2024-01-30T19:16:04.060Z[Etc/UTC]")
public class V1beta1WorkshopSpecSessionApplicationsDockerCompose {
  public static final String SERIALIZED_NAME_SERVICES = "services";
  @SerializedName(SERIALIZED_NAME_SERVICES)
  private Object services;

  public static final String SERIALIZED_NAME_VOLUMES = "volumes";
  @SerializedName(SERIALIZED_NAME_VOLUMES)
  private Object volumes;


  public V1beta1WorkshopSpecSessionApplicationsDockerCompose services(Object services) {
    
    this.services = services;
    return this;
  }

   /**
   * Get services
   * @return services
  **/
  @ApiModelProperty(required = true, value = "")

  public Object getServices() {
    return services;
  }


  public void setServices(Object services) {
    this.services = services;
  }


  public V1beta1WorkshopSpecSessionApplicationsDockerCompose volumes(Object volumes) {
    
    this.volumes = volumes;
    return this;
  }

   /**
   * Get volumes
   * @return volumes
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Object getVolumes() {
    return volumes;
  }


  public void setVolumes(Object volumes) {
    this.volumes = volumes;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSpecSessionApplicationsDockerCompose v1beta1WorkshopSpecSessionApplicationsDockerCompose = (V1beta1WorkshopSpecSessionApplicationsDockerCompose) o;
    return Objects.equals(this.services, v1beta1WorkshopSpecSessionApplicationsDockerCompose.services) &&
        Objects.equals(this.volumes, v1beta1WorkshopSpecSessionApplicationsDockerCompose.volumes);
  }

  @Override
  public int hashCode() {
    return Objects.hash(services, volumes);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSpecSessionApplicationsDockerCompose {\n");
    sb.append("    services: ").append(toIndentedString(services)).append("\n");
    sb.append("    volumes: ").append(toIndentedString(volumes)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

