/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.tanzu.learningcenter.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.learningcenter.models.V1beta1SystemProfileSpecDockerdMirror;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1SystemProfileSpecDockerd
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-07T20:08:06.732Z[Etc/UTC]")
public class V1beta1SystemProfileSpecDockerd {
  public static final String SERIALIZED_NAME_MIRROR = "mirror";
  @SerializedName(SERIALIZED_NAME_MIRROR)
  private V1beta1SystemProfileSpecDockerdMirror mirror;

  public static final String SERIALIZED_NAME_MTU = "mtu";
  @SerializedName(SERIALIZED_NAME_MTU)
  private Integer mtu;

  public static final String SERIALIZED_NAME_PRIVILEGED = "privileged";
  @SerializedName(SERIALIZED_NAME_PRIVILEGED)
  private Boolean privileged;

  public static final String SERIALIZED_NAME_ROOTLESS = "rootless";
  @SerializedName(SERIALIZED_NAME_ROOTLESS)
  private Boolean rootless;


  public V1beta1SystemProfileSpecDockerd mirror(V1beta1SystemProfileSpecDockerdMirror mirror) {
    
    this.mirror = mirror;
    return this;
  }

   /**
   * Get mirror
   * @return mirror
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SystemProfileSpecDockerdMirror getMirror() {
    return mirror;
  }


  public void setMirror(V1beta1SystemProfileSpecDockerdMirror mirror) {
    this.mirror = mirror;
  }


  public V1beta1SystemProfileSpecDockerd mtu(Integer mtu) {
    
    this.mtu = mtu;
    return this;
  }

   /**
   * Get mtu
   * @return mtu
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Integer getMtu() {
    return mtu;
  }


  public void setMtu(Integer mtu) {
    this.mtu = mtu;
  }


  public V1beta1SystemProfileSpecDockerd privileged(Boolean privileged) {
    
    this.privileged = privileged;
    return this;
  }

   /**
   * Get privileged
   * @return privileged
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getPrivileged() {
    return privileged;
  }


  public void setPrivileged(Boolean privileged) {
    this.privileged = privileged;
  }


  public V1beta1SystemProfileSpecDockerd rootless(Boolean rootless) {
    
    this.rootless = rootless;
    return this;
  }

   /**
   * Get rootless
   * @return rootless
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public Boolean getRootless() {
    return rootless;
  }


  public void setRootless(Boolean rootless) {
    this.rootless = rootless;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SystemProfileSpecDockerd v1beta1SystemProfileSpecDockerd = (V1beta1SystemProfileSpecDockerd) o;
    return Objects.equals(this.mirror, v1beta1SystemProfileSpecDockerd.mirror) &&
        Objects.equals(this.mtu, v1beta1SystemProfileSpecDockerd.mtu) &&
        Objects.equals(this.privileged, v1beta1SystemProfileSpecDockerd.privileged) &&
        Objects.equals(this.rootless, v1beta1SystemProfileSpecDockerd.rootless);
  }

  @Override
  public int hashCode() {
    return Objects.hash(mirror, mtu, privileged, rootless);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SystemProfileSpecDockerd {\n");
    sb.append("    mirror: ").append(toIndentedString(mirror)).append("\n");
    sb.append("    mtu: ").append(toIndentedString(mtu)).append("\n");
    sb.append("    privileged: ").append(toIndentedString(privileged)).append("\n");
    sb.append("    rootless: ").append(toIndentedString(rootless)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

