/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.tanzu.learningcenter.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.learningcenter.models.V1beta1TrainingPortalSpecAnalyticsGoogle;
import com.vmware.tanzu.learningcenter.models.V1beta1TrainingPortalSpecAnalyticsWebhook;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1TrainingPortalSpecAnalytics
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-07T20:08:06.732Z[Etc/UTC]")
public class V1beta1TrainingPortalSpecAnalytics {
  public static final String SERIALIZED_NAME_GOOGLE = "google";
  @SerializedName(SERIALIZED_NAME_GOOGLE)
  private V1beta1TrainingPortalSpecAnalyticsGoogle google;

  public static final String SERIALIZED_NAME_WEBHOOK = "webhook";
  @SerializedName(SERIALIZED_NAME_WEBHOOK)
  private V1beta1TrainingPortalSpecAnalyticsWebhook webhook;


  public V1beta1TrainingPortalSpecAnalytics google(V1beta1TrainingPortalSpecAnalyticsGoogle google) {
    
    this.google = google;
    return this;
  }

   /**
   * Get google
   * @return google
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecAnalyticsGoogle getGoogle() {
    return google;
  }


  public void setGoogle(V1beta1TrainingPortalSpecAnalyticsGoogle google) {
    this.google = google;
  }


  public V1beta1TrainingPortalSpecAnalytics webhook(V1beta1TrainingPortalSpecAnalyticsWebhook webhook) {
    
    this.webhook = webhook;
    return this;
  }

   /**
   * Get webhook
   * @return webhook
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecAnalyticsWebhook getWebhook() {
    return webhook;
  }


  public void setWebhook(V1beta1TrainingPortalSpecAnalyticsWebhook webhook) {
    this.webhook = webhook;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1TrainingPortalSpecAnalytics v1beta1TrainingPortalSpecAnalytics = (V1beta1TrainingPortalSpecAnalytics) o;
    return Objects.equals(this.google, v1beta1TrainingPortalSpecAnalytics.google) &&
        Objects.equals(this.webhook, v1beta1TrainingPortalSpecAnalytics.webhook);
  }

  @Override
  public int hashCode() {
    return Objects.hash(google, webhook);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1TrainingPortalSpecAnalytics {\n");
    sb.append("    google: ").append(toIndentedString(google)).append("\n");
    sb.append("    webhook: ").append(toIndentedString(webhook)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

