/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.tanzu.learningcenter.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1SystemProfileSpecThemeDashboard
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-07T20:08:06.732Z[Etc/UTC]")
public class V1beta1SystemProfileSpecThemeDashboard {
  public static final String SERIALIZED_NAME_SCRIPT = "script";
  @SerializedName(SERIALIZED_NAME_SCRIPT)
  private String script;

  public static final String SERIALIZED_NAME_STYLE = "style";
  @SerializedName(SERIALIZED_NAME_STYLE)
  private String style;


  public V1beta1SystemProfileSpecThemeDashboard script(String script) {
    
    this.script = script;
    return this;
  }

   /**
   * Get script
   * @return script
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getScript() {
    return script;
  }


  public void setScript(String script) {
    this.script = script;
  }


  public V1beta1SystemProfileSpecThemeDashboard style(String style) {
    
    this.style = style;
    return this;
  }

   /**
   * Get style
   * @return style
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getStyle() {
    return style;
  }


  public void setStyle(String style) {
    this.style = style;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SystemProfileSpecThemeDashboard v1beta1SystemProfileSpecThemeDashboard = (V1beta1SystemProfileSpecThemeDashboard) o;
    return Objects.equals(this.script, v1beta1SystemProfileSpecThemeDashboard.script) &&
        Objects.equals(this.style, v1beta1SystemProfileSpecThemeDashboard.style);
  }

  @Override
  public int hashCode() {
    return Objects.hash(script, style);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SystemProfileSpecThemeDashboard {\n");
    sb.append("    script: ").append(toIndentedString(script)).append("\n");
    sb.append("    style: ").append(toIndentedString(style)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

