/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.tanzu.learningcenter.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSpecSessionApplicationsConsole;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSpecSessionApplicationsDocker;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSpecSessionApplicationsEditor;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSpecSessionApplicationsFiles;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSpecSessionApplicationsTerminal;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSpecSessionApplicationsWorkshop;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1WorkshopSpecSessionApplications
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-07T20:08:06.732Z[Etc/UTC]")
public class V1beta1WorkshopSpecSessionApplications {
  public static final String SERIALIZED_NAME_CONSOLE = "console";
  @SerializedName(SERIALIZED_NAME_CONSOLE)
  private V1beta1WorkshopSpecSessionApplicationsConsole console;

  public static final String SERIALIZED_NAME_DOCKER = "docker";
  @SerializedName(SERIALIZED_NAME_DOCKER)
  private V1beta1WorkshopSpecSessionApplicationsDocker docker;

  public static final String SERIALIZED_NAME_EDITOR = "editor";
  @SerializedName(SERIALIZED_NAME_EDITOR)
  private V1beta1WorkshopSpecSessionApplicationsEditor editor;

  public static final String SERIALIZED_NAME_EXAMINER = "examiner";
  @SerializedName(SERIALIZED_NAME_EXAMINER)
  private V1beta1WorkshopSpecSessionApplicationsEditor examiner;

  public static final String SERIALIZED_NAME_FILES = "files";
  @SerializedName(SERIALIZED_NAME_FILES)
  private V1beta1WorkshopSpecSessionApplicationsFiles files;

  public static final String SERIALIZED_NAME_REGISTRY = "registry";
  @SerializedName(SERIALIZED_NAME_REGISTRY)
  private V1beta1WorkshopSpecSessionApplicationsDocker registry;

  public static final String SERIALIZED_NAME_SLIDES = "slides";
  @SerializedName(SERIALIZED_NAME_SLIDES)
  private V1beta1WorkshopSpecSessionApplicationsEditor slides;

  public static final String SERIALIZED_NAME_TERMINAL = "terminal";
  @SerializedName(SERIALIZED_NAME_TERMINAL)
  private V1beta1WorkshopSpecSessionApplicationsTerminal terminal;

  public static final String SERIALIZED_NAME_WEBDAV = "webdav";
  @SerializedName(SERIALIZED_NAME_WEBDAV)
  private V1beta1WorkshopSpecSessionApplicationsEditor webdav;

  public static final String SERIALIZED_NAME_WORKSHOP = "workshop";
  @SerializedName(SERIALIZED_NAME_WORKSHOP)
  private V1beta1WorkshopSpecSessionApplicationsWorkshop workshop;


  public V1beta1WorkshopSpecSessionApplications console(V1beta1WorkshopSpecSessionApplicationsConsole console) {
    
    this.console = console;
    return this;
  }

   /**
   * Get console
   * @return console
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsConsole getConsole() {
    return console;
  }


  public void setConsole(V1beta1WorkshopSpecSessionApplicationsConsole console) {
    this.console = console;
  }


  public V1beta1WorkshopSpecSessionApplications docker(V1beta1WorkshopSpecSessionApplicationsDocker docker) {
    
    this.docker = docker;
    return this;
  }

   /**
   * Get docker
   * @return docker
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsDocker getDocker() {
    return docker;
  }


  public void setDocker(V1beta1WorkshopSpecSessionApplicationsDocker docker) {
    this.docker = docker;
  }


  public V1beta1WorkshopSpecSessionApplications editor(V1beta1WorkshopSpecSessionApplicationsEditor editor) {
    
    this.editor = editor;
    return this;
  }

   /**
   * Get editor
   * @return editor
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsEditor getEditor() {
    return editor;
  }


  public void setEditor(V1beta1WorkshopSpecSessionApplicationsEditor editor) {
    this.editor = editor;
  }


  public V1beta1WorkshopSpecSessionApplications examiner(V1beta1WorkshopSpecSessionApplicationsEditor examiner) {
    
    this.examiner = examiner;
    return this;
  }

   /**
   * Get examiner
   * @return examiner
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsEditor getExaminer() {
    return examiner;
  }


  public void setExaminer(V1beta1WorkshopSpecSessionApplicationsEditor examiner) {
    this.examiner = examiner;
  }


  public V1beta1WorkshopSpecSessionApplications files(V1beta1WorkshopSpecSessionApplicationsFiles files) {
    
    this.files = files;
    return this;
  }

   /**
   * Get files
   * @return files
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsFiles getFiles() {
    return files;
  }


  public void setFiles(V1beta1WorkshopSpecSessionApplicationsFiles files) {
    this.files = files;
  }


  public V1beta1WorkshopSpecSessionApplications registry(V1beta1WorkshopSpecSessionApplicationsDocker registry) {
    
    this.registry = registry;
    return this;
  }

   /**
   * Get registry
   * @return registry
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsDocker getRegistry() {
    return registry;
  }


  public void setRegistry(V1beta1WorkshopSpecSessionApplicationsDocker registry) {
    this.registry = registry;
  }


  public V1beta1WorkshopSpecSessionApplications slides(V1beta1WorkshopSpecSessionApplicationsEditor slides) {
    
    this.slides = slides;
    return this;
  }

   /**
   * Get slides
   * @return slides
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsEditor getSlides() {
    return slides;
  }


  public void setSlides(V1beta1WorkshopSpecSessionApplicationsEditor slides) {
    this.slides = slides;
  }


  public V1beta1WorkshopSpecSessionApplications terminal(V1beta1WorkshopSpecSessionApplicationsTerminal terminal) {
    
    this.terminal = terminal;
    return this;
  }

   /**
   * Get terminal
   * @return terminal
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsTerminal getTerminal() {
    return terminal;
  }


  public void setTerminal(V1beta1WorkshopSpecSessionApplicationsTerminal terminal) {
    this.terminal = terminal;
  }


  public V1beta1WorkshopSpecSessionApplications webdav(V1beta1WorkshopSpecSessionApplicationsEditor webdav) {
    
    this.webdav = webdav;
    return this;
  }

   /**
   * Get webdav
   * @return webdav
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsEditor getWebdav() {
    return webdav;
  }


  public void setWebdav(V1beta1WorkshopSpecSessionApplicationsEditor webdav) {
    this.webdav = webdav;
  }


  public V1beta1WorkshopSpecSessionApplications workshop(V1beta1WorkshopSpecSessionApplicationsWorkshop workshop) {
    
    this.workshop = workshop;
    return this;
  }

   /**
   * Get workshop
   * @return workshop
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSpecSessionApplicationsWorkshop getWorkshop() {
    return workshop;
  }


  public void setWorkshop(V1beta1WorkshopSpecSessionApplicationsWorkshop workshop) {
    this.workshop = workshop;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSpecSessionApplications v1beta1WorkshopSpecSessionApplications = (V1beta1WorkshopSpecSessionApplications) o;
    return Objects.equals(this.console, v1beta1WorkshopSpecSessionApplications.console) &&
        Objects.equals(this.docker, v1beta1WorkshopSpecSessionApplications.docker) &&
        Objects.equals(this.editor, v1beta1WorkshopSpecSessionApplications.editor) &&
        Objects.equals(this.examiner, v1beta1WorkshopSpecSessionApplications.examiner) &&
        Objects.equals(this.files, v1beta1WorkshopSpecSessionApplications.files) &&
        Objects.equals(this.registry, v1beta1WorkshopSpecSessionApplications.registry) &&
        Objects.equals(this.slides, v1beta1WorkshopSpecSessionApplications.slides) &&
        Objects.equals(this.terminal, v1beta1WorkshopSpecSessionApplications.terminal) &&
        Objects.equals(this.webdav, v1beta1WorkshopSpecSessionApplications.webdav) &&
        Objects.equals(this.workshop, v1beta1WorkshopSpecSessionApplications.workshop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(console, docker, editor, examiner, files, registry, slides, terminal, webdav, workshop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSpecSessionApplications {\n");
    sb.append("    console: ").append(toIndentedString(console)).append("\n");
    sb.append("    docker: ").append(toIndentedString(docker)).append("\n");
    sb.append("    editor: ").append(toIndentedString(editor)).append("\n");
    sb.append("    examiner: ").append(toIndentedString(examiner)).append("\n");
    sb.append("    files: ").append(toIndentedString(files)).append("\n");
    sb.append("    registry: ").append(toIndentedString(registry)).append("\n");
    sb.append("    slides: ").append(toIndentedString(slides)).append("\n");
    sb.append("    terminal: ").append(toIndentedString(terminal)).append("\n");
    sb.append("    webdav: ").append(toIndentedString(webdav)).append("\n");
    sb.append("    workshop: ").append(toIndentedString(workshop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

