/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.tanzu.learningcenter.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.learningcenter.models.V1beta1TrainingPortalSpecPortalClients;
import com.vmware.tanzu.learningcenter.models.V1beta1TrainingPortalSpecPortalCredentials;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1SystemProfileSpecPortal
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-07T20:08:06.732Z[Etc/UTC]")
public class V1beta1SystemProfileSpecPortal {
  public static final String SERIALIZED_NAME_CLIENTS = "clients";
  @SerializedName(SERIALIZED_NAME_CLIENTS)
  private V1beta1TrainingPortalSpecPortalClients clients;

  public static final String SERIALIZED_NAME_CREDENTIALS = "credentials";
  @SerializedName(SERIALIZED_NAME_CREDENTIALS)
  private V1beta1TrainingPortalSpecPortalCredentials credentials;

  public static final String SERIALIZED_NAME_IMAGE = "image";
  @SerializedName(SERIALIZED_NAME_IMAGE)
  private String image;


  public V1beta1SystemProfileSpecPortal clients(V1beta1TrainingPortalSpecPortalClients clients) {
    
    this.clients = clients;
    return this;
  }

   /**
   * Get clients
   * @return clients
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalClients getClients() {
    return clients;
  }


  public void setClients(V1beta1TrainingPortalSpecPortalClients clients) {
    this.clients = clients;
  }


  public V1beta1SystemProfileSpecPortal credentials(V1beta1TrainingPortalSpecPortalCredentials credentials) {
    
    this.credentials = credentials;
    return this;
  }

   /**
   * Get credentials
   * @return credentials
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecPortalCredentials getCredentials() {
    return credentials;
  }


  public void setCredentials(V1beta1TrainingPortalSpecPortalCredentials credentials) {
    this.credentials = credentials;
  }


  public V1beta1SystemProfileSpecPortal image(String image) {
    
    this.image = image;
    return this;
  }

   /**
   * Get image
   * @return image
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public String getImage() {
    return image;
  }


  public void setImage(String image) {
    this.image = image;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SystemProfileSpecPortal v1beta1SystemProfileSpecPortal = (V1beta1SystemProfileSpecPortal) o;
    return Objects.equals(this.clients, v1beta1SystemProfileSpecPortal.clients) &&
        Objects.equals(this.credentials, v1beta1SystemProfileSpecPortal.credentials) &&
        Objects.equals(this.image, v1beta1SystemProfileSpecPortal.image);
  }

  @Override
  public int hashCode() {
    return Objects.hash(clients, credentials, image);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SystemProfileSpecPortal {\n");
    sb.append("    clients: ").append(toIndentedString(clients)).append("\n");
    sb.append("    credentials: ").append(toIndentedString(credentials)).append("\n");
    sb.append("    image: ").append(toIndentedString(image)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

