/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.tanzu.learningcenter.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.learningcenter.models.V1beta1TrainingPortalSpecSystem;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSessionSpecAnalytics;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSessionSpecEnvironment;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSessionSpecRequest;
import com.vmware.tanzu.learningcenter.models.V1beta1WorkshopSessionSpecSession;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1WorkshopSessionSpec
 */
@javax.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-07T20:08:06.732Z[Etc/UTC]")
public class V1beta1WorkshopSessionSpec {
  public static final String SERIALIZED_NAME_ANALYTICS = "analytics";
  @SerializedName(SERIALIZED_NAME_ANALYTICS)
  private V1beta1WorkshopSessionSpecAnalytics analytics;

  public static final String SERIALIZED_NAME_ENVIRONMENT = "environment";
  @SerializedName(SERIALIZED_NAME_ENVIRONMENT)
  private V1beta1WorkshopSessionSpecEnvironment environment;

  public static final String SERIALIZED_NAME_REQUEST = "request";
  @SerializedName(SERIALIZED_NAME_REQUEST)
  private V1beta1WorkshopSessionSpecRequest request;

  public static final String SERIALIZED_NAME_SESSION = "session";
  @SerializedName(SERIALIZED_NAME_SESSION)
  private V1beta1WorkshopSessionSpecSession session;

  public static final String SERIALIZED_NAME_SYSTEM = "system";
  @SerializedName(SERIALIZED_NAME_SYSTEM)
  private V1beta1TrainingPortalSpecSystem system;


  public V1beta1WorkshopSessionSpec analytics(V1beta1WorkshopSessionSpecAnalytics analytics) {
    
    this.analytics = analytics;
    return this;
  }

   /**
   * Get analytics
   * @return analytics
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSessionSpecAnalytics getAnalytics() {
    return analytics;
  }


  public void setAnalytics(V1beta1WorkshopSessionSpecAnalytics analytics) {
    this.analytics = analytics;
  }


  public V1beta1WorkshopSessionSpec environment(V1beta1WorkshopSessionSpecEnvironment environment) {
    
    this.environment = environment;
    return this;
  }

   /**
   * Get environment
   * @return environment
  **/
  @ApiModelProperty(required = true, value = "")

  public V1beta1WorkshopSessionSpecEnvironment getEnvironment() {
    return environment;
  }


  public void setEnvironment(V1beta1WorkshopSessionSpecEnvironment environment) {
    this.environment = environment;
  }


  public V1beta1WorkshopSessionSpec request(V1beta1WorkshopSessionSpecRequest request) {
    
    this.request = request;
    return this;
  }

   /**
   * Get request
   * @return request
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSessionSpecRequest getRequest() {
    return request;
  }


  public void setRequest(V1beta1WorkshopSessionSpecRequest request) {
    this.request = request;
  }


  public V1beta1WorkshopSessionSpec session(V1beta1WorkshopSessionSpecSession session) {
    
    this.session = session;
    return this;
  }

   /**
   * Get session
   * @return session
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1WorkshopSessionSpecSession getSession() {
    return session;
  }


  public void setSession(V1beta1WorkshopSessionSpecSession session) {
    this.session = session;
  }


  public V1beta1WorkshopSessionSpec system(V1beta1TrainingPortalSpecSystem system) {
    
    this.system = system;
    return this;
  }

   /**
   * Get system
   * @return system
  **/
  @javax.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1TrainingPortalSpecSystem getSystem() {
    return system;
  }


  public void setSystem(V1beta1TrainingPortalSpecSystem system) {
    this.system = system;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1WorkshopSessionSpec v1beta1WorkshopSessionSpec = (V1beta1WorkshopSessionSpec) o;
    return Objects.equals(this.analytics, v1beta1WorkshopSessionSpec.analytics) &&
        Objects.equals(this.environment, v1beta1WorkshopSessionSpec.environment) &&
        Objects.equals(this.request, v1beta1WorkshopSessionSpec.request) &&
        Objects.equals(this.session, v1beta1WorkshopSessionSpec.session) &&
        Objects.equals(this.system, v1beta1WorkshopSessionSpec.system);
  }

  @Override
  public int hashCode() {
    return Objects.hash(analytics, environment, request, session, system);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1WorkshopSessionSpec {\n");
    sb.append("    analytics: ").append(toIndentedString(analytics)).append("\n");
    sb.append("    environment: ").append(toIndentedString(environment)).append("\n");
    sb.append("    request: ").append(toIndentedString(request)).append("\n");
    sb.append("    session: ").append(toIndentedString(session)).append("\n");
    sb.append("    system: ").append(toIndentedString(system)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

