/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.tanzu.learningcenter.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;

/**
 * V1beta1SystemProfileSpecNetwork
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-07T20:08:06.732Z[Etc/UTC]")
public class V1beta1SystemProfileSpecNetwork {
  public static final String SERIALIZED_NAME_BLOCK_C_I_D_RS = "blockCIDRs";
  @SerializedName(SERIALIZED_NAME_BLOCK_C_I_D_RS)
  private List<String> blockCIDRs = null;


  public V1beta1SystemProfileSpecNetwork blockCIDRs(List<String> blockCIDRs) {
    
    this.blockCIDRs = blockCIDRs;
    return this;
  }

  public V1beta1SystemProfileSpecNetwork addBlockCIDRsItem(String blockCIDRsItem) {
    if (this.blockCIDRs == null) {
      this.blockCIDRs = new ArrayList<>();
    }
    this.blockCIDRs.add(blockCIDRsItem);
    return this;
  }

   /**
   * Get blockCIDRs
   * @return blockCIDRs
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public List<String> getBlockCIDRs() {
    return blockCIDRs;
  }


  public void setBlockCIDRs(List<String> blockCIDRs) {
    this.blockCIDRs = blockCIDRs;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SystemProfileSpecNetwork v1beta1SystemProfileSpecNetwork = (V1beta1SystemProfileSpecNetwork) o;
    return Objects.equals(this.blockCIDRs, v1beta1SystemProfileSpecNetwork.blockCIDRs);
  }

  @Override
  public int hashCode() {
    return Objects.hash(blockCIDRs);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SystemProfileSpecNetwork {\n");
    sb.append("    blockCIDRs: ").append(toIndentedString(blockCIDRs)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

