/*
 * Kubernetes
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1.21.1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


package com.vmware.tanzu.learningcenter.models;

import java.util.Objects;
import java.util.Arrays;
import com.google.gson.TypeAdapter;
import com.google.gson.annotations.JsonAdapter;
import com.google.gson.annotations.SerializedName;
import com.google.gson.stream.JsonReader;
import com.google.gson.stream.JsonWriter;
import com.vmware.tanzu.learningcenter.models.V1beta1SystemProfileSpecThemeDashboard;
import io.swagger.annotations.ApiModel;
import io.swagger.annotations.ApiModelProperty;
import java.io.IOException;

/**
 * V1beta1SystemProfileSpecTheme
 */
@jakarta.annotation.Generated(value = "org.openapitools.codegen.languages.JavaClientCodegen", date = "2022-03-07T20:08:06.732Z[Etc/UTC]")
public class V1beta1SystemProfileSpecTheme {
  public static final String SERIALIZED_NAME_DASHBOARD = "dashboard";
  @SerializedName(SERIALIZED_NAME_DASHBOARD)
  private V1beta1SystemProfileSpecThemeDashboard dashboard;

  public static final String SERIALIZED_NAME_PORTAL = "portal";
  @SerializedName(SERIALIZED_NAME_PORTAL)
  private V1beta1SystemProfileSpecThemeDashboard portal;

  public static final String SERIALIZED_NAME_WORKSHOP = "workshop";
  @SerializedName(SERIALIZED_NAME_WORKSHOP)
  private V1beta1SystemProfileSpecThemeDashboard workshop;


  public V1beta1SystemProfileSpecTheme dashboard(V1beta1SystemProfileSpecThemeDashboard dashboard) {
    
    this.dashboard = dashboard;
    return this;
  }

   /**
   * Get dashboard
   * @return dashboard
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SystemProfileSpecThemeDashboard getDashboard() {
    return dashboard;
  }


  public void setDashboard(V1beta1SystemProfileSpecThemeDashboard dashboard) {
    this.dashboard = dashboard;
  }


  public V1beta1SystemProfileSpecTheme portal(V1beta1SystemProfileSpecThemeDashboard portal) {
    
    this.portal = portal;
    return this;
  }

   /**
   * Get portal
   * @return portal
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SystemProfileSpecThemeDashboard getPortal() {
    return portal;
  }


  public void setPortal(V1beta1SystemProfileSpecThemeDashboard portal) {
    this.portal = portal;
  }


  public V1beta1SystemProfileSpecTheme workshop(V1beta1SystemProfileSpecThemeDashboard workshop) {
    
    this.workshop = workshop;
    return this;
  }

   /**
   * Get workshop
   * @return workshop
  **/
  @jakarta.annotation.Nullable
  @ApiModelProperty(value = "")

  public V1beta1SystemProfileSpecThemeDashboard getWorkshop() {
    return workshop;
  }


  public void setWorkshop(V1beta1SystemProfileSpecThemeDashboard workshop) {
    this.workshop = workshop;
  }


  @Override
  public boolean equals(Object o) {
    if (this == o) {
      return true;
    }
    if (o == null || getClass() != o.getClass()) {
      return false;
    }
    V1beta1SystemProfileSpecTheme v1beta1SystemProfileSpecTheme = (V1beta1SystemProfileSpecTheme) o;
    return Objects.equals(this.dashboard, v1beta1SystemProfileSpecTheme.dashboard) &&
        Objects.equals(this.portal, v1beta1SystemProfileSpecTheme.portal) &&
        Objects.equals(this.workshop, v1beta1SystemProfileSpecTheme.workshop);
  }

  @Override
  public int hashCode() {
    return Objects.hash(dashboard, portal, workshop);
  }


  @Override
  public String toString() {
    StringBuilder sb = new StringBuilder();
    sb.append("class V1beta1SystemProfileSpecTheme {\n");
    sb.append("    dashboard: ").append(toIndentedString(dashboard)).append("\n");
    sb.append("    portal: ").append(toIndentedString(portal)).append("\n");
    sb.append("    workshop: ").append(toIndentedString(workshop)).append("\n");
    sb.append("}");
    return sb.toString();
  }

  /**
   * Convert the given object to string with each line indented by 4 spaces
   * (except the first line).
   */
  private String toIndentedString(Object o) {
    if (o == null) {
      return "null";
    }
    return o.toString().replace("\n", "\n    ");
  }

}

